import type { LocalRuntimeLifecycleResult } from '../client';
import type { LocalRuntimeServiceDescriptor } from '../service';

export type KiteServiceManagerOperation = 'ensure' | 'status' | 'stop' | 'restart';

export type KiteServiceManagerProcessStatus = 'dead' | 'alive' | 'uncertain';

export interface KiteServiceManagerRequest {
  /** Caller-provided correlation id; generated by the manager when omitted. */
  readonly requestId?: string;
  /** A mismatched revision is rejected before any descriptor or child is touched. */
  readonly clientContractRevision?: string;
  /** Source/installed executable selection is explicit and never inferred from cwd. */
  readonly executableMode?: 'source' | 'installed';
}

export interface KiteServiceManagerEnvironment {
  readonly cwd: string;
  readonly env: Readonly<Record<string, string>>;
}

export interface KiteServiceManagerEnvironmentPort {
  resolve(): Promise<KiteServiceManagerEnvironment>;
}

export interface KiteServiceManagerStatePort {
  /** Raw input is decoded by the manager so malformed state fails closed. */
  readDescriptor(): Promise<unknown | undefined>;
  readToken(kind: 'access' | 'control'): Promise<string | undefined>;
  /** Strict instance-lock identity used for descriptor publication crash-window recovery. */
  readInstanceLock(): Promise<unknown | undefined>;
  /** Remove a descriptor/token published by a confirmed-dead process only. */
  clearStale(): Promise<void>;
  /** Keep evidence when a startup/stop resource cannot be closed safely. */
  preserveFailure(): Promise<void>;
}

export interface KiteServiceManagerLifecycleLockLease extends AsyncDisposable {
  release(): Promise<void>;
}

export interface KiteServiceManagerLifecycleLockPort {
  /** Atomic directory lock acquisition. Undefined means another owner currently holds it. */
  acquire(
    operation: KiteServiceManagerOperation,
  ): Promise<KiteServiceManagerLifecycleLockLease | undefined>;
  /** Strict owner/PID inspection used only after acquire reports contention. */
  inspect(): Promise<
    | { readonly status: 'absent' }
    | {
        readonly status: KiteServiceManagerProcessStatus;
        readonly pid?: number;
      }
  >;
  /** Isolate a lock only after the owner process is confirmed dead. */
  quarantineStale(): Promise<void>;
}

export interface KiteServiceManagerHandshake {
  readonly outcome: 'healthy' | 'incompatible' | 'unavailable';
  readonly instanceId?: string;
  readonly protocolVersion?: number;
  readonly clientContractRevision?: string;
  /** Server-owned version returned by the authenticated instance handshake. */
  readonly serverVersion?: string;
  readonly buildId?: string;
  readonly diagnostic?:
    | 'protocol_incompatible'
    | 'client_contract_incompatible'
    | 'identity_uncertain';
}

export interface KiteServiceManagerProbePort {
  handshake(input: {
    readonly descriptor: LocalRuntimeServiceDescriptor;
    readonly accessToken: string;
  }): Promise<KiteServiceManagerHandshake>;
}

export interface KiteServiceManagerProcessPort {
  inspect(pid: number): Promise<KiteServiceManagerProcessStatus>;
}

export interface KiteServiceManagerExecutable {
  readonly path: string;
  readonly mode: 'source' | 'installed';
  readonly buildId?: string;
}

export interface KiteServiceManagerExecutableResolver {
  resolve(mode: 'source' | 'installed'): Promise<KiteServiceManagerExecutable>;
}

export interface KiteServiceManagerReadinessSignal {
  /** Exact instance id sent over an independent readiness pipe/handle. */
  readonly instanceId: string;
}

/**
 * The readiness transport is a one-shot native resource (pipe/handle), not a child-process
 * lifecycle owner. Releasing it must never signal, terminate, or otherwise control the child.
 */
export interface KiteServiceManagerReadinessPort {
  release(): Promise<void>;
}

/** Backwards-compatible descriptive alias for callers that model the one-shot handle directly. */
export type KiteServiceManagerReadinessHandle = KiteServiceManagerReadinessPort;

export interface KiteServiceManagerChild {
  readonly pid: number;
  readonly readiness: KiteServiceManagerReadinessPort;
  waitForReady(): Promise<KiteServiceManagerReadinessSignal>;
}

export interface KiteServiceManagerSpawnPort {
  spawn(input: {
    readonly executable: KiteServiceManagerExecutable;
    readonly args: readonly string[];
    readonly cwd: string;
    readonly env: Readonly<Record<string, string>>;
    readonly detached: true;
    /** stdout is never a readiness/protocol channel. */
    readonly stdout: 'ignore';
  }): Promise<KiteServiceManagerChild>;
}

export interface KiteServiceManagerControlResult {
  readonly outcome: 'applied' | 'service_busy' | 'outcome_unknown' | 'unavailable';
  readonly diagnostic?: 'service_busy' | 'service_unavailable' | 'identity_uncertain';
}

export interface KiteServiceManagerControlPort {
  stop(input: {
    readonly descriptor: LocalRuntimeServiceDescriptor;
    readonly controlToken: string;
    readonly requestId: string;
  }): Promise<KiteServiceManagerControlResult>;
}

export interface KiteServiceManagerOptions {
  readonly state: KiteServiceManagerStatePort;
  readonly lifecycleLock: KiteServiceManagerLifecycleLockPort;
  readonly probe: KiteServiceManagerProbePort;
  readonly process: KiteServiceManagerProcessPort;
  readonly environment: KiteServiceManagerEnvironmentPort;
  readonly executableResolver: KiteServiceManagerExecutableResolver;
  readonly spawn: KiteServiceManagerSpawnPort;
  readonly control: KiteServiceManagerControlPort;
  readonly protocolVersion?: number;
  readonly clientContractRevision?: string;
  readonly expectedBuildId?: string;
  readonly startupTimeoutMs?: number;
  readonly operationTimeoutMs?: number;
}

export interface KiteServiceManager {
  ensure(request?: KiteServiceManagerRequest): Promise<LocalRuntimeLifecycleResult>;
  status(request?: KiteServiceManagerRequest): Promise<LocalRuntimeLifecycleResult>;
  stop(request?: KiteServiceManagerRequest): Promise<LocalRuntimeLifecycleResult>;
  restart(request?: KiteServiceManagerRequest): Promise<LocalRuntimeLifecycleResult>;
}
