import { platform, release, type } from "node:os";
import type { BaseMessage } from "@langchain/core/messages";
import type { AgentPlan } from "@/protocol/events";

/** 运行时系统信息 / Runtime system information */
export interface RuntimeSystemInfo {
  /** 当前时间 ISO 格式 / Current time in ISO format */
  currentTimeIso: string;
  /** 时区 / Timezone */
  timezone: string;
  /** 操作系统类型 / OS type */
  os: string;
  /** 平台 / Platform */
  platform: string;
  /** 系统版本 / OS release version */
  release: string;
  /** 当前 Shell / Current shell */
  shell: string;
  /** 当前工作目录 / Current working directory */
  cwd: string;
  /** 工作区路径 / Workspace path */
  workspace: string;
}

/** 运行时上下文输入参数 / Runtime context input parameters */
export interface RuntimeContextInput {
  /** 工作目录 / Workspace path */
  workspace: string;
  /** 对话消息 / Conversation messages */
  messages: BaseMessage[];
  /** 工作区访问权限 / Workspace access level */
  workspaceAccess?: "write";
  /** 执行计划 / Execution plan */
  plan?: AgentPlan | null;
  /** 可注入的当前时间 / Injectable current time */
  now?: Date;
  /** 可注入的时区 / Injectable timezone */
  timezone?: string;
}

/** 可缓存运行时上下文输入 — 仅包含 session 稳定的字段 / Cacheable runtime context input — only session-stable fields */
export interface CacheableRuntimeContextInput {
  /** 工作目录 / Workspace path (stable within a session) */
  workspace: string;
}

/** 收集运行时系统信息 / Collect runtime system information */
export function getRuntimeSystemInfo(input: {
  workspace: string;
  now?: Date;
  timezone?: string;
}): RuntimeSystemInfo {
  const now = input.now ?? new Date();
  return {
    currentTimeIso: now.toISOString(),
    timezone: input.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone,
    os: type(),
    platform: platform(),
    release: release(),
    shell: process.env.SHELL || "bash",
    cwd: process.cwd(),
    workspace: input.workspace,
  };
}

/** 构建动态运行时上下文（含时间戳，不适合缓存）/ Build dynamic runtime context (includes timestamps, not cacheable) */
export function buildRuntimeContext(input: RuntimeContextInput): string {
  const info = getRuntimeSystemInfo(input);
  const lines = [
    "Dynamic runtime context:",
    `Time: ${info.currentTimeIso}`,
    `Timezone: ${info.timezone}`,
    `OS: ${info.os} ${info.release} (${info.platform})`,
    `Shell: ${info.shell}`,
    `CWD: ${info.cwd}`,
    `Workspace: ${info.workspace}`,
  ];

  return lines.join("\n");
}

/**
 * 构建可缓存的运行时上下文（不含时间戳，适合 provider 前缀缓存）。
 *
 * **缓存契约**：此函数的输出在同一 session 内必须保持稳定。不得在此函数中
 * 注入任何逐请求变化的值（时间戳、token 计数、动态 skill 指令、上下文摘要等），
 * 否则会破坏 DeepSeek 等 provider 的前缀缓存命中机制。
 *
 * Build cacheable runtime context (no timestamps, cache-stable for provider prefix caching).
 *
 * **Cache contract**: The output of this function MUST remain stable within a session.
 * Do NOT inject any per-request variable values (timestamps, token counts, dynamic skill
 * instructions, context summaries, etc.) into this function, as it would break prefix cache
 * hit for providers like DeepSeek.
 */
export function buildCacheableRuntimeContext(input: CacheableRuntimeContextInput): string {
  const { workspace } = input;
  const osType = type();
  const osPlatform = platform();
  const shellPath = process.env.SHELL || "bash";
  const lines = [
    "Cacheable runtime context:",
    `OS: ${osType} (${osPlatform})`,
    `Shell: ${shellPath} — use ${shellPath} syntax for shell_execute, NOT PowerShell or cmd.exe`,
    `Workspace: ${workspace}`,
  ];
  return lines.join("\n");
}

/** 将计划格式化为运行时状态提醒文本 / Format plan as runtime state reminder text */
export function formatPlanStateReminder(plan: NonNullable<RuntimeContextInput["plan"]>): string {
  const lines = [
    '<runtime-state source="graph.state.plan">',
    "This message is generated by the harness, not by the user.",
    "Use it as the current persisted plan state.",
    `Name: ${plan.name}`,
    `Status: ${plan.status}`,
    `Description: ${plan.description}`,
    "Steps:",
    ...plan.steps.map((step) => `- [${step.status}] ${step.step}`),
    "</runtime-state>",
  ];
  return lines.join("\n");
}
