import { platform, release, type } from "node:os";
import type { BaseMessage } from "@langchain/core/messages";
import type { AgentPlan, WorkspaceAccess } from "../shared/types";

/** 运行时系统信息 / Runtime system information */
export interface RuntimeSystemInfo {
  /** 当前时间 ISO 格式 / Current time in ISO format */
  currentTimeIso: string;
  /** 时区 / Timezone */
  timezone: string;
  /** 操作系统类型 / OS type */
  os: string;
  /** 平台 / Platform */
  platform: string;
  /** 系统版本 / OS release version */
  release: string;
  /** 当前 Shell / Current shell */
  shell: string;
  /** 当前工作目录 / Current working directory */
  cwd: string;
  /** 工作区路径 / Workspace path */
  workspace: string;
}

/** 运行时上下文输入参数 / Runtime context input parameters */
export interface RuntimeContextInput {
  /** 工作目录 / Workspace path */
  workspace: string;
  /** 对话消息 / Conversation messages */
  messages: BaseMessage[];
  /** 工作区访问权限 / Workspace access level */
  workspaceAccess?: WorkspaceAccess;
  /** 执行计划 / Execution plan */
  plan?: AgentPlan | null;
  /** 上下文摘要 / Context summary */
  contextSummary?: string;
  /** 可注入的当前时间 / Injectable current time */
  now?: Date;
  /** 可注入的时区 / Injectable timezone */
  timezone?: string;
}

/** 收集运行时系统信息 / Collect runtime system information */
export function getRuntimeSystemInfo(input: {
  workspace: string;
  now?: Date;
  timezone?: string;
}): RuntimeSystemInfo {
  const now = input.now ?? new Date();
  return {
    currentTimeIso: now.toISOString(),
    timezone: input.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone,
    os: type(),
    platform: platform(),
    release: release(),
    shell: process.env.SHELL || process.env.ComSpec || "powershell",
    cwd: process.cwd(),
    workspace: input.workspace,
  };
}

/** 构建动态运行时上下文（含时间戳，不适合缓存）/ Build dynamic runtime context (includes timestamps, not cacheable) */
export function buildRuntimeContext(input: RuntimeContextInput): string {
  const info = getRuntimeSystemInfo(input);
  const lines = [
    "Dynamic runtime context:",
    `Time: ${info.currentTimeIso}`,
    `Timezone: ${info.timezone}`,
    `OS: ${info.os} ${info.release} (${info.platform})`,
    `Shell: ${info.shell}`,
    `CWD: ${info.cwd}`,
    `Workspace: ${info.workspace}`,
    `Workspace access policy: ${workspaceAccessPolicy()}`,
  ];

  return lines.join("\n");
}

/** 构建可缓存的运行时上下文（不含时间戳，适合 provider 前缀缓存）/ Build cacheable runtime context (no timestamps, cache-stable for provider prefix caching) */
export function buildCacheableRuntimeContext(input: RuntimeContextInput): string {
  const lines = [
    "Cacheable runtime context:",
    `Workspace: ${input.workspace}`,
    `Workspace access policy: ${workspaceAccessPolicy()}`,
  ];

  return lines.join("\n");
}

/** 将当前工作区访问权限格式化为尾部运行时状态提醒 / Format current workspace access as a trailing runtime state reminder */
export function formatWorkspaceAccessReminder(workspaceAccess: WorkspaceAccess): string {
  const lines = [
    '<runtime-state source="graph.state.workspaceAccess">',
    "This message is generated by the harness, not by the user.",
    `Current workspace access: ${workspaceAccess}`,
    workspaceAccess === "read-only"
      ? "Tool execution boundary: read-only access; write/delete/execute tools are rejected."
      : "Tool execution boundary: write access; write/delete/execute tools require approval.",
    "</runtime-state>",
  ];
  return lines.join("\n");
}

/** 将计划格式化为运行时状态提醒文本 / Format plan as runtime state reminder text */
export function formatPlanStateReminder(plan: NonNullable<RuntimeContextInput["plan"]>): string {
  const lines = [
    '<runtime-state source="graph.state.plan">',
    "This message is generated by the harness, not by the user.",
    "Use it as the current persisted plan state.",
    `Name: ${plan.name}`,
    `Status: ${plan.status}`,
    `Description: ${plan.description}`,
    "Steps:",
    ...plan.steps.map((step) => `- [${step.status}] ${step.step}`),
    "</runtime-state>",
  ];
  return lines.join("\n");
}

/** 返回跨访问权限稳定的工作区访问策略 / Return cache-stable workspace access policy */
function workspaceAccessPolicy(): string {
  return "visible tool schemas are cache-stable; the model may call update_plan when planning helps and ask_user when clarification is needed; read-only access rejects write/delete/execute tools; write access requires approval for write/delete/execute tools";
}
