//! Versioned, strictly framed control messages between the adapter and runner.
//!
//! The transport is a 4-byte little-endian length prefix followed by one
//! UTF-8 JSON control frame. The length prefix is only framing; it is not
//! an integrity boundary. Every request, cancellation, output chunk, and
//! terminal receipt is bound to the directly inherited stdin/stdout pipes.

use serde::de::DeserializeOwned;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use base64::Engine;

/// Matches `WINDOWS_SANDBOX_PROTOCOL_VERSION` on the TypeScript side.
pub const PROTOCOL_VERSION: u32 = 6;
pub const HOST_PEER_ID: &str = "host";
pub const RUNNER_PEER_ID: &str = "runner";
pub const MAX_FRAME_BYTES: usize = 16 * 1024 * 1024;

/// Per-invocation state for the direct restricted-token backend. The runtime
/// capability is generated by the trusted adapter so its unique ACL can be
/// revoked by `--cleanup` if the runner crashes. A startup probe also supplies
/// an ephemeral Workspace capability; normal commands use the native
/// persistent per-Workspace capability ledger instead.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DirectWorkspaceConfig {
    pub runtime_capability_sid: String,
    #[serde(default)]
    pub approved_filesystem_guard_sid: Option<String>,
    #[serde(default)]
    pub ephemeral_workspace_capability_sid: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct InvocationRequest {
    pub version: u32,
    pub direct_workspace: DirectWorkspaceConfig,
    /// Invocation-unique identity generated by the trusted adapter.
    pub invocation_name: String,
    /// Full command line to execute inside the sandboxed shell.
    pub command_line: String,
    /// Canonical working directory (the Workspace root).
    pub cwd: String,
    /// Minimal environment allowlist built by the adapter.
    pub env: std::collections::BTreeMap<String, String>,
    /// `workspace_write`, `read_only`, or one user-approved `full_access` invocation.
    pub filesystem_scope: FilesystemScope,
    /// Canonical Workspace root (realpath).
    pub workspace_root: String,
    /// Invocation-private runtime directory (rw for the sandbox).
    pub runtime_root: String,
    /// Root of the vendored Shell runtime (read+execute for the sandbox).
    pub shell_runtime_root: String,
    /// The fixed entrypoint of the release-pinned runtime. The runner never
    /// probes this directory for a more-preferred executable.
    pub shell_runtime: ShellRuntime,
    /// Expected SHA-256 (hex, no prefix) of that runtime entrypoint.
    pub shell_runtime_digest: String,
    /// Expected SHA-256 of the fixed Microsoft Coreutils multi-call binary in
    /// `shell_runtime_root`.
    pub coreutils_digest: String,
    /// Hard active-process limit for the Job Object.
    pub max_processes: u32,
    /// Execution timeout in milliseconds.
    pub timeout_ms: u64,
    /// Per-invocation network authorization.
    pub network_mode: NetworkMode,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FilesystemScope {
    WorkspaceWrite,
    ReadOnly,
    FullAccess,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ShellRuntime {
    Bash,
    Busybox,
    Isksh,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NetworkMode {
    Off,
    AllowAll,
}

/// Generic control frame. `type`, peer, invocation, and sequence are checked
/// together with the payload. The strict
/// top-level shape is intentional: adding a field is a protocol change, not
/// something an older runner may silently ignore.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ControlFrame {
    #[serde(rename = "type")]
    pub frame_type: String,
    pub version: u32,
    #[serde(rename = "invocationId")]
    pub invocation_id: String,
    #[serde(rename = "peerId")]
    pub peer_id: String,
    pub sequence: u64,
    #[serde(rename = "payloadBase64")]
    pub payload_base64: String,
}

#[derive(Debug, Clone)]
pub struct VerifiedControlFrame<T> {
    pub frame: ControlFrame,
    pub payload: T,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CancelPayload {}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ReadyPayload {
    pub invocation_name: String,
    pub runtime_validated: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct GoPayload {
    pub invocation_name: String,
    pub supervisor_acknowledged: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OutputPayload {
    pub data: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct LogPayload {
    pub level: String,
    pub message: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ExecutionReceipt {
    pub version: u32,
    pub exit_code: u32,
    pub timed_out: bool,
    pub cancelled: bool,
    pub stdout_bytes: u64,
    pub stderr_bytes: u64,
    pub peak_processes: u32,
    pub active_process_limit: u32,
    pub cleanup_confirmed: bool,
    pub invocation_name: String,
    /// Typed error code; `null` when the command ran.
    pub error: Option<String>,
}

/// Encode one length-prefixed transport frame. The caller must validate
/// the JSON before invoking this helper; the prefix itself has no security meaning.
pub fn encode_frame(value: &impl Serialize) -> std::io::Result<Vec<u8>> {
    let value = serde_json::to_value(value)?;
    let json = canonical_json(&value)
        .map_err(|error| std::io::Error::new(std::io::ErrorKind::InvalidData, error))?
        .into_bytes();
    if json.len() > MAX_FRAME_BYTES {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            "frame exceeds maximum length",
        ));
    }
    let mut frame = Vec::with_capacity(4 + json.len());
    let length = u32::try_from(json.len()).map_err(|_| {
        std::io::Error::new(std::io::ErrorKind::InvalidData, "frame exceeds u32 length")
    })?;
    frame.extend_from_slice(&length.to_le_bytes());
    frame.extend_from_slice(&json);
    Ok(frame)
}

/// Decode one length-prefixed frame. Oversized and truncated frames fail
/// closed before any payload is deserialized or dispatched.
pub fn decode_frame(reader: &mut impl std::io::Read) -> std::io::Result<Vec<u8>> {
    let mut length_bytes = [0u8; 4];
    reader.read_exact(&mut length_bytes)?;
    let length = u32::from_le_bytes(length_bytes) as usize;
    if length > MAX_FRAME_BYTES {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            "frame exceeds maximum length",
        ));
    }
    let mut payload = vec![0u8; length];
    reader.read_exact(&mut payload)?;
    Ok(payload)
}

#[derive(Debug)]
pub enum ProtocolError {
    Io(std::io::Error),
    Json(serde_json::Error),
    VersionMismatch { expected: u32, actual: u32 },
    InvalidFrame(String),
}

impl std::fmt::Display for ProtocolError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ProtocolError::Io(error) => write!(formatter, "io error: {error}"),
            ProtocolError::Json(error) => write!(formatter, "json error: {error}"),
            ProtocolError::VersionMismatch { expected, actual } => write!(
                formatter,
                "protocol version mismatch: expected {expected}, got {actual}"
            ),
            ProtocolError::InvalidFrame(message) => write!(formatter, "invalid frame: {message}"),
        }
    }
}

impl From<std::io::Error> for ProtocolError {
    fn from(error: std::io::Error) -> Self {
        ProtocolError::Io(error)
    }
}

impl From<serde_json::Error> for ProtocolError {
    fn from(error: serde_json::Error) -> Self {
        ProtocolError::Json(error)
    }
}

/// Return a deterministic JSON representation with object keys sorted at
/// every level. The TypeScript adapter uses the same canonical form.
pub fn canonical_json(value: &Value) -> Result<String, serde_json::Error> {
    match value {
        Value::Null | Value::Bool(_) | Value::Number(_) | Value::String(_) => {
            serde_json::to_string(value)
        }
        Value::Array(values) => {
            let mut output = String::from("[");
            for (index, child) in values.iter().enumerate() {
                if index > 0 {
                    output.push(',');
                }
                output.push_str(&canonical_json(child)?);
            }
            output.push(']');
            Ok(output)
        }
        Value::Object(values) => {
            let mut keys = values.keys().collect::<Vec<_>>();
            keys.sort();
            let mut output = String::from("{");
            for (index, key) in keys.iter().enumerate() {
                if index > 0 {
                    output.push(',');
                }
                output.push_str(&serde_json::to_string(key)?);
                output.push(':');
                let child = values
                    .get(key.as_str())
                    .expect("canonical object key must exist");
                output.push_str(&canonical_json(child)?);
            }
            output.push('}');
            Ok(output)
        }
    }
}

/// Encode one strict control frame for the native-to-host or host-to-native direction.
pub fn encode_control_frame<T: Serialize>(
    frame_type: &str,
    invocation_id: &str,
    peer_id: &str,
    sequence: u64,
    payload: &T,
) -> Result<Vec<u8>, ProtocolError> {
    let payload_value = serde_json::to_value(payload)?;
    let payload_json = canonical_json(&payload_value)?;
    let payload_base64 = base64::engine::general_purpose::STANDARD.encode(payload_json.as_bytes());
    let frame = ControlFrame {
        frame_type: frame_type.to_string(),
        version: PROTOCOL_VERSION,
        invocation_id: invocation_id.to_string(),
        peer_id: peer_id.to_string(),
        sequence,
        payload_base64,
    };
    Ok(encode_frame(&frame)?)
}

/// Verify one control frame before deserializing or dispatching its typed
/// payload. Exactly the expected peer, invocation, and next sequence are
/// accepted; this gives replay and cross-invocation failures deterministic
/// fail-closed behavior.
pub fn decode_control_frame<T: DeserializeOwned>(
    payload: &[u8],
    expected_type: &str,
    expected_peer_id: &str,
    expected_invocation_id: &str,
    expected_sequence: u64,
) -> Result<VerifiedControlFrame<T>, ProtocolError> {
    let raw: ControlFrame = serde_json::from_slice(payload)?;
    let raw_value: Value = serde_json::from_slice(payload)?;
    if canonical_json(&raw_value)?.as_bytes() != payload {
        return Err(ProtocolError::InvalidFrame("outer frame is not canonical".to_string()));
    }
    if raw.version != PROTOCOL_VERSION {
        return Err(ProtocolError::VersionMismatch {
            expected: PROTOCOL_VERSION,
            actual: raw.version,
        });
    }
    if raw.frame_type != expected_type
        || raw.peer_id != expected_peer_id
        || raw.invocation_id != expected_invocation_id
        || raw.sequence != expected_sequence
    {
        return Err(ProtocolError::InvalidFrame(
            "control frame identity or sequence mismatch".to_string(),
        ));
    }
    let payload_bytes = base64::engine::general_purpose::STANDARD
        .decode(&raw.payload_base64)
        .map_err(|_| ProtocolError::InvalidFrame("control payload base64 is invalid".to_string()))?;
    if base64::engine::general_purpose::STANDARD.encode(&payload_bytes) != raw.payload_base64 {
        return Err(ProtocolError::InvalidFrame(
            "control payload base64 is not canonical".to_string(),
        ));
    }
    let payload_value: Value = serde_json::from_slice(&payload_bytes)
        .map_err(|error| ProtocolError::InvalidFrame(format!("control payload json is invalid: {error}")))?;
    if canonical_json(&payload_value)?.as_bytes() != payload_bytes {
        return Err(ProtocolError::InvalidFrame("control payload is not canonical".to_string()));
    }
    let typed: T = serde_json::from_slice(&payload_bytes).map_err(|error| {
        ProtocolError::InvalidFrame(format!("control payload shape is invalid: {error}"))
    })?;
    Ok(VerifiedControlFrame { frame: raw, payload: typed })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn control_frame_round_trips() {
        let encoded = encode_control_frame(
            "stdout",
            "kitecode.invocation",
            RUNNER_PEER_ID,
            0,
            &OutputPayload {
                data: "aGVsbG8=".to_string(),
            },
        )
        .unwrap();
        let mut cursor = std::io::Cursor::new(encoded);
        let payload = decode_frame(&mut cursor).unwrap();
        let decoded = decode_control_frame::<OutputPayload>(
            &payload,
            "stdout",
            RUNNER_PEER_ID,
            "kitecode.invocation",
            0,
        )
        .unwrap();
        assert_eq!(decoded.payload.data, "aGVsbG8=");
    }

    #[test]
    fn ready_and_go_are_directional_and_sequence_bound() {
        let ready = encode_control_frame(
            "ready",
            "kitecode.invocation",
            RUNNER_PEER_ID,
            0,
            &ReadyPayload {
                invocation_name: "kitecode.invocation".to_string(),
                runtime_validated: true,
            },
        )
        .unwrap();
        let ready_payload = decode_frame(&mut std::io::Cursor::new(ready)).unwrap();
        assert!(decode_control_frame::<ReadyPayload>(
            &ready_payload,
            "ready",
            RUNNER_PEER_ID,
            "kitecode.invocation",
            0,
        )
        .is_ok());

        let go = encode_control_frame(
            "go",
            "kitecode.invocation",
            HOST_PEER_ID,
            1,
            &GoPayload {
                invocation_name: "kitecode.invocation".to_string(),
                supervisor_acknowledged: true,
            },
        )
        .unwrap();
        let go_payload = decode_frame(&mut std::io::Cursor::new(go)).unwrap();
        assert!(decode_control_frame::<GoPayload>(
            &go_payload,
            "go",
            HOST_PEER_ID,
            "kitecode.invocation",
            1,
        )
        .is_ok());
    }

    #[test]
    fn wrong_peer_replay_and_unknown_field_fail_closed() {
        let encoded = encode_control_frame(
            "cancel",
            "kitecode.invocation",
            HOST_PEER_ID,
            1,
            &CancelPayload {},
        )
        .unwrap();
        let mut cursor = std::io::Cursor::new(encoded.clone());
        let payload = decode_frame(&mut cursor).unwrap();
        assert!(decode_control_frame::<CancelPayload>(
            &payload,
            "cancel",
            HOST_PEER_ID,
            "kitecode.invocation",
            1,
        )
        .is_ok());
        assert!(decode_control_frame::<CancelPayload>(
            &payload,
            "cancel",
            RUNNER_PEER_ID,
            "kitecode.invocation",
            1,
        )
        .is_err());
        assert!(decode_control_frame::<CancelPayload>(
            &payload,
            "cancel",
            HOST_PEER_ID,
            "kitecode.invocation",
            0,
        )
        .is_err());
        let mut value: Value = serde_json::from_slice(&payload).unwrap();
        value["unexpected"] = Value::Bool(true);
        let tampered = encode_frame(&value).unwrap();
        let tampered_payload = tampered[4..].to_vec();
        assert!(decode_control_frame::<CancelPayload>(
            &tampered_payload,
            "cancel",
            HOST_PEER_ID,
            "kitecode.invocation",
            1,
        )
        .is_err());
    }

    #[test]
    fn truncated_frame_is_rejected() {
        let mut cursor = std::io::Cursor::new(vec![8, 0, 0, 0, b'{']);
        assert!(decode_frame(&mut cursor).is_err());
    }

    #[test]
    fn canonical_outer_and_payload_reject_duplicate_whitespace_unicode_and_edge_vectors() {
        let encoded = encode_control_frame(
            "stdout",
            "kitecode.invocation",
            RUNNER_PEER_ID,
            0,
            &OutputPayload {
                data: "aGVsbG8=".to_string(),
            },
        )
        .unwrap();
        let payload = decode_frame(&mut std::io::Cursor::new(encoded)).unwrap();
        let outer = String::from_utf8(payload.clone()).unwrap();
        let duplicate_outer = outer.replacen("\"type\":\"stdout\",", "\"type\":\"stdout\",\"type\":\"stdout\",", 1);
        assert!(decode_control_frame::<OutputPayload>(
            duplicate_outer.as_bytes(),
            "stdout",
            RUNNER_PEER_ID,
            "kitecode.invocation",
            0,
        )
        .is_err());
        let whitespace_outer = format!(" {outer} ");
        assert!(decode_control_frame::<OutputPayload>(
            whitespace_outer.as_bytes(),
            "stdout",
            RUNNER_PEER_ID,
            "kitecode.invocation",
            0,
        )
        .is_err());

        let mut frame: ControlFrame = serde_json::from_slice(&payload).unwrap();
        let duplicate_payload = br#"{"data":"aGVsbG8=","data":"aGVsbG8="}"#;
        frame.payload_base64 = base64::engine::general_purpose::STANDARD.encode(duplicate_payload);
        let duplicate_payload_frame = encode_frame(&frame).unwrap();
        let duplicate_payload_bytes = decode_frame(&mut std::io::Cursor::new(duplicate_payload_frame)).unwrap();
        assert!(decode_control_frame::<OutputPayload>(
            &duplicate_payload_bytes,
            "stdout",
            RUNNER_PEER_ID,
            "kitecode.invocation",
            0,
        )
        .is_err());

        let unicode_number = serde_json::json!({
            "env": {"🦄": "é"},
            "number": 9_007_199_254_740_991u64,
        });
        let canonical = canonical_json(&unicode_number).unwrap();
        assert!(canonical.contains("🦄"));
        assert!(canonical.contains("9007199254740991"));
    }
}
