//! Versioned, framed protocol between the Bun/TypeScript adapter and this
//! native runner.
//!
//! Frame = 4-byte little-endian length prefix + UTF-8 JSON payload. The
//! adapter writes exactly one request frame on stdin; the runner streams
//! response frames on stdout and ends with an `exit` frame carrying a
//! structured execution receipt.

use serde::{Deserialize, Serialize};

/// Matches `WINDOWS_SANDBOX_PROTOCOL_VERSION` on the TypeScript side.
pub const PROTOCOL_VERSION: u32 = 5;

/// Per-invocation state for the direct restricted-token backend. The runtime
/// capability is generated by the trusted adapter so its unique ACL can be
/// revoked by `--cleanup` if the runner crashes. A startup probe also supplies
/// an ephemeral Workspace capability; normal commands use the native
/// persistent per-Workspace capability ledger instead.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DirectWorkspaceConfig {
    pub runtime_capability_sid: String,
    #[serde(default)]
    pub ephemeral_workspace_capability_sid: Option<String>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InvocationRequest {
    pub version: u32,
    pub direct_workspace: DirectWorkspaceConfig,
    /// Invocation-unique identity generated by the trusted adapter.
    pub invocation_name: String,
    /// Full command line to execute inside the sandboxed shell.
    pub command_line: String,
    /// Canonical working directory (the Workspace root).
    pub cwd: String,
    /// Minimal environment allowlist built by the adapter.
    pub env: std::collections::BTreeMap<String, String>,
    /// `workspace_write` or `read_only`.
    pub filesystem_scope: FilesystemScope,
    /// Canonical Workspace root (realpath).
    pub workspace_root: String,
    /// Invocation-private runtime directory (rw for the sandbox).
    pub runtime_root: String,
    /// Root of the vendored Shell runtime (read+execute for the sandbox).
    pub shell_runtime_root: String,
    /// The fixed entrypoint of the release-pinned runtime.  The runner never
    /// probes this directory for a more-preferred executable.
    pub shell_runtime: ShellRuntime,
    /// Expected SHA-256 (hex, no prefix) of that runtime entrypoint.
    pub shell_runtime_digest: String,
    /// Expected SHA-256 of the fixed Microsoft Coreutils multi-call binary in
    /// `shell_runtime_root`. The runner materializes command-name aliases in
    /// the invocation-private runtime only after checking this digest.
    pub coreutils_digest: String,
    /// Hard active-process limit for the Job Object.
    pub max_processes: u32,
    /// Execution timeout in milliseconds.
    pub timeout_ms: u64,
    /// Per-invocation network authorization. Protocol V5 requires the runner to relaunch
    /// an approved `allow_all` request in the provisioned online login session.
    pub network_mode: NetworkMode,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FilesystemScope {
    WorkspaceWrite,
    ReadOnly,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ShellRuntime {
    Bash,
    Busybox,
    Isksh,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NetworkMode {
    Off,
    AllowAll,
}

pub fn requires_managed_online_identity(network_mode: NetworkMode) -> bool {
    matches!(network_mode, NetworkMode::AllowAll)
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum OutboundFrame {
    #[serde(rename_all = "camelCase")]
    Log {
        level: String,
        message: String,
    },
    Stdout {
        data: String,
    },
    Stderr {
        data: String,
    },
    Exit {
        receipt: ExecutionReceipt,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExecutionReceipt {
    pub version: u32,
    pub exit_code: u32,
    pub timed_out: bool,
    pub cancelled: bool,
    pub stdout_bytes: u64,
    pub stderr_bytes: u64,
    pub peak_processes: u32,
    pub active_process_limit: u32,
    pub cleanup_confirmed: bool,
    pub invocation_name: String,
    /// Typed error code; `null` when the command ran.
    pub error: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CancelFrame {
    #[serde(rename = "type")]
    pub kind: String,
}

/// Encode one frame as 4-byte LE length + JSON bytes.
pub fn encode_frame(value: &impl Serialize) -> std::io::Result<Vec<u8>> {
    let json = serde_json::to_vec(value)?;
    let mut frame = Vec::with_capacity(4 + json.len());
    let length = u32::try_from(json.len()).map_err(|_| {
        std::io::Error::new(std::io::ErrorKind::InvalidData, "frame exceeds u32 length")
    })?;
    frame.extend_from_slice(&length.to_le_bytes());
    frame.extend_from_slice(&json);
    Ok(frame)
}

/// Decode one frame from a stream of length-prefixed frames.
pub fn decode_frame(reader: &mut impl std::io::Read) -> std::io::Result<Vec<u8>> {
    let mut length_bytes = [0u8; 4];
    reader.read_exact(&mut length_bytes)?;
    let length = u32::from_le_bytes(length_bytes) as usize;
    let mut payload = vec![0u8; length];
    reader.read_exact(&mut payload)?;
    Ok(payload)
}

#[derive(Debug)]
pub enum ProtocolError {
    Io(std::io::Error),
    Json(serde_json::Error),
    VersionMismatch { expected: u32, actual: u32 },
    InvalidFrame(String),
}

impl std::fmt::Display for ProtocolError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ProtocolError::Io(error) => write!(formatter, "io error: {error}"),
            ProtocolError::Json(error) => write!(formatter, "json error: {error}"),
            ProtocolError::VersionMismatch { expected, actual } => {
                write!(
                    formatter,
                    "protocol version mismatch: expected {expected}, got {actual}"
                )
            }
            ProtocolError::InvalidFrame(message) => write!(formatter, "invalid frame: {message}"),
        }
    }
}

impl From<std::io::Error> for ProtocolError {
    fn from(error: std::io::Error) -> Self {
        ProtocolError::Io(error)
    }
}

impl From<serde_json::Error> for ProtocolError {
    fn from(error: serde_json::Error) -> Self {
        ProtocolError::Json(error)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn frame_round_trips() {
        let frame = OutboundFrame::Stdout {
            data: "hello".to_string(),
        };
        let encoded = encode_frame(&frame).unwrap();
        let mut cursor = std::io::Cursor::new(encoded);
        let payload = decode_frame(&mut cursor).unwrap();
        let decoded: OutboundFrame = serde_json::from_slice(&payload).unwrap();
        match decoded {
            OutboundFrame::Stdout { data } => assert_eq!(data, "hello"),
            _ => panic!("wrong frame type"),
        }
    }

    #[test]
    fn frame_length_is_prefixed() {
        let frame = OutboundFrame::Log {
            level: "info".to_string(),
            message: "x".repeat(300),
        };
        let encoded = encode_frame(&frame).unwrap();
        assert_eq!(
            u32::from_le_bytes([encoded[0], encoded[1], encoded[2], encoded[3]]) as usize + 4,
            encoded.len()
        );
    }

    #[test]
    fn network_mode_serializes_the_explicit_allow_all_grant() {
        assert_eq!(
            serde_json::to_string(&NetworkMode::AllowAll).unwrap(),
            r#""allow_all""#
        );
    }

    #[test]
    fn allow_all_uses_the_managed_online_identity() {
        assert!(requires_managed_online_identity(NetworkMode::AllowAll));
        assert!(!requires_managed_online_identity(NetworkMode::Off));
    }
}
