import {
  RAV1_AUTHORITY_SEQUENCE_V1,
  RAV1_AUTHORITY_THREAT_MODEL_SCHEMA_V1,
  type Rav1AuthorityThreatModelV1,
} from '@kite/runtime-spi';

/**
 * RAV1-00 source-fact inventory. It records current RMV1 boundaries without
 * claiming that deferred RAV1 authenticity or target formats already exist.
 */
export const RAV1_00_BOUNDARY_INVENTORY_V1 = Object.freeze({
  schema: RAV1_AUTHORITY_THREAT_MODEL_SCHEMA_V1,
  trustedInProcessActors: ['agent_kernel', 'runtime_host', 'builtin_runtime'],
  sequence: RAV1_AUTHORITY_SEQUENCE_V1,
  excludedAttackers: [
    'malicious_trusted_in_process_runtime',
    'compromised_operating_system_or_kernel',
    'arbitrary_process_memory_read',
  ],
  boundaries: [
    {
      boundaryId: 'client_command',
      carrier: 'in_process_typed',
      runtimeActors: ['runtime_host'],
      boundaryActors: ['client'],
      sourceTrust: ['untrusted_input'],
      serialized: false,
      persisted: false,
      authorityBearing: false,
      secretMaterialAllowed: false,
      authenticity: 'not_applicable_schema_and_identity_only',
      keyCustody: 'none',
      attackerClasses: ['untrusted_client_input', 'identity_mixup_or_trusted_code_bug'],
    },
    {
      boundaryId: 'trusted_runtime_typed_authority',
      carrier: 'in_process_typed',
      runtimeActors: ['agent_kernel', 'runtime_host', 'builtin_runtime'],
      boundaryActors: [],
      sourceTrust: ['trusted_runtime'],
      serialized: false,
      persisted: false,
      authorityBearing: true,
      secretMaterialAllowed: false,
      authenticity: 'not_applicable_schema_and_identity_only',
      keyCustody: 'none',
      attackerClasses: ['identity_mixup_or_trusted_code_bug', 'clock_rollback'],
    },
    {
      boundaryId: 'runtime_store_records',
      carrier: 'persisted_serialized',
      runtimeActors: ['runtime_host'],
      boundaryActors: ['storage_adapter'],
      sourceTrust: ['trusted_runtime', 'local_same_user_state'],
      serialized: true,
      persisted: true,
      authorityBearing: true,
      secretMaterialAllowed: false,
      authenticity: 'keyless_integrity_only',
      keyCustody: 'none',
      attackerClasses: [
        'same_user_persisted_state_tamper',
        'stale_or_replayed_record',
        'cross_host_or_process_race',
      ],
    },
    {
      boundaryId: 'private_artifact_files',
      carrier: 'persisted_serialized',
      runtimeActors: ['builtin_runtime'],
      boundaryActors: ['artifact_store'],
      sourceTrust: ['trusted_runtime', 'local_same_user_state'],
      serialized: true,
      persisted: true,
      authorityBearing: true,
      secretMaterialAllowed: false,
      authenticity: 'existing_authenticated_storage',
      keyCustody: 'installation_owner_file',
      attackerClasses: ['same_user_persisted_state_tamper', 'stale_or_replayed_record'],
    },
    {
      boundaryId: 'posix_sandbox_control_protocol',
      carrier: 'out_of_process_protocol',
      runtimeActors: ['runtime_host', 'sandbox_supervisor'],
      boundaryActors: ['sandbox_worker'],
      sourceTrust: ['trusted_runtime', 'untrusted_child_process'],
      serialized: true,
      persisted: false,
      authorityBearing: true,
      secretMaterialAllowed: false,
      authenticity: 'peer_or_message_authentication_required',
      keyCustody: 'invocation_local_material',
      attackerClasses: [
        'untrusted_child_process',
        'stale_or_replayed_record',
        'identity_mixup_or_trusted_code_bug',
      ],
    },
    {
      boundaryId: 'windows_sandbox_runner_protocol',
      carrier: 'out_of_process_protocol',
      runtimeActors: ['runtime_host', 'sandbox_supervisor'],
      boundaryActors: ['sandbox_worker'],
      sourceTrust: ['trusted_runtime', 'untrusted_child_process'],
      serialized: true,
      persisted: false,
      authorityBearing: true,
      secretMaterialAllowed: false,
      authenticity: 'peer_or_message_authentication_required',
      keyCustody: 'invocation_local_material',
      attackerClasses: [
        'untrusted_child_process',
        'stale_or_replayed_record',
        'identity_mixup_or_trusted_code_bug',
      ],
    },
    {
      boundaryId: 'filesystem_and_process_effect',
      carrier: 'external_resource',
      runtimeActors: ['builtin_runtime'],
      boundaryActors: ['filesystem_or_process'],
      sourceTrust: ['trusted_runtime', 'local_same_user_state'],
      serialized: false,
      persisted: false,
      authorityBearing: true,
      secretMaterialAllowed: false,
      authenticity: 'not_applicable_schema_and_identity_only',
      keyCustody: 'none',
      attackerClasses: ['identity_mixup_or_trusted_code_bug', 'same_user_persisted_state_tamper'],
    },
    {
      boundaryId: 'mcp_http_transport',
      carrier: 'out_of_process_protocol',
      runtimeActors: ['builtin_runtime'],
      boundaryActors: ['mcp_endpoint'],
      sourceTrust: ['trusted_runtime', 'untrusted_remote_endpoint'],
      serialized: true,
      persisted: false,
      authorityBearing: true,
      secretMaterialAllowed: false,
      authenticity: 'external_transport_or_os_broker',
      keyCustody: 'transport_or_os_peer_identity',
      attackerClasses: [
        'untrusted_remote_endpoint',
        'stale_or_replayed_record',
        'identity_mixup_or_trusted_code_bug',
      ],
    },
    {
      boundaryId: 'mcp_stdio_transport',
      carrier: 'out_of_process_protocol',
      runtimeActors: ['builtin_runtime'],
      boundaryActors: ['mcp_endpoint'],
      sourceTrust: ['trusted_runtime', 'untrusted_child_process'],
      serialized: true,
      persisted: false,
      authorityBearing: true,
      secretMaterialAllowed: false,
      authenticity: 'peer_or_message_authentication_required',
      keyCustody: 'invocation_local_material',
      attackerClasses: [
        'untrusted_child_process',
        'stale_or_replayed_record',
        'identity_mixup_or_trusted_code_bug',
      ],
    },
    {
      boundaryId: 'model_provider_transport',
      carrier: 'out_of_process_protocol',
      runtimeActors: ['builtin_runtime'],
      boundaryActors: ['model_endpoint'],
      sourceTrust: ['trusted_runtime', 'untrusted_remote_endpoint'],
      serialized: true,
      persisted: false,
      authorityBearing: true,
      secretMaterialAllowed: false,
      authenticity: 'external_transport_or_os_broker',
      keyCustody: 'transport_or_os_peer_identity',
      attackerClasses: [
        'untrusted_remote_endpoint',
        'stale_or_replayed_record',
        'identity_mixup_or_trusted_code_bug',
      ],
    },
    {
      boundaryId: 'credential_vault',
      carrier: 'persisted_serialized',
      runtimeActors: ['builtin_runtime'],
      boundaryActors: ['credential_broker'],
      sourceTrust: ['trusted_runtime', 'trusted_os_broker'],
      serialized: true,
      persisted: true,
      authorityBearing: true,
      secretMaterialAllowed: false,
      authenticity: 'external_transport_or_os_broker',
      keyCustody: 'os_credential_vault',
      attackerClasses: ['identity_mixup_or_trusted_code_bug', 'stale_or_replayed_record'],
    },
    {
      boundaryId: 'client_notification_projection',
      carrier: 'non_authoritative_projection',
      runtimeActors: ['runtime_host'],
      boundaryActors: ['client'],
      sourceTrust: ['trusted_runtime'],
      serialized: false,
      persisted: false,
      authorityBearing: false,
      secretMaterialAllowed: false,
      authenticity: 'not_authority',
      keyCustody: 'none',
      attackerClasses: ['identity_mixup_or_trusted_code_bug'],
    },
  ],
} as const satisfies Rav1AuthorityThreatModelV1);
