import type { BaseMessage } from '@langchain/core/messages';
import { Annotation, messagesStateReducer } from '@langchain/langgraph';
import { type AutoReviewState, DEFAULT_AUTO_REVIEW_STATE } from '@/core/execution/circuit-breaker';
import type { ExecutionJournalEntry } from '@/core/execution/journal';
import type { PermitBatch } from '@/core/execution/permit';
import type { SandboxBackend } from '@/core/sandbox/platform';
import type { SubAgentContinuation } from '@/core/subagent/types';
import type { ContextBudget, ThreadAuthorizationState } from '@/core/types';
import type {
  AgentPhase,
  AgentPlan,
  InteractionMode,
  ShellGrantUsed,
  WorkspaceAccess,
} from '@/protocol/events';
import { defaultAuthorizationState } from './tool-policy';
import type { PendingToolRequest } from './tool-requests';

export interface PendingSubAgentApproval {
  taskCallId: string;
  request: PendingToolRequest;
  continuation: SubAgentContinuation;
}

export const AgentState = Annotation.Root({
  /** 用户 ID / User ID */
  userId: Annotation<string>,
  /** LangGraph 线程 ID / LangGraph thread ID */
  threadId: Annotation<string>({
    reducer: (_left, right) => right,
    default: () => '',
  }),
  /** 工作目录路径 / Workspace path */
  workspace: Annotation<string>,
  /** 工作区访问权限 read-only/write / Workspace access level (read-only/write) */
  workspaceAccess: Annotation<WorkspaceAccess>({
    reducer: (_left, right) => right,
    default: () => 'write',
  }),
  /** Agent 执行阶段 planning/building / Agent execution phase */
  phase: Annotation<AgentPhase>({
    reducer: (_left, right) => right,
    default: () => 'building',
  }),
  /** 审批节点生成的当前工具请求覆盖 / Current tool request override generated by approval */
  approvedToolRequest: Annotation<PendingToolRequest | null>({
    reducer: (_left, right) => right,
    default: () => null,
  }),
  /** 当前已审批工具请求使用的授权类型 / Grant used by the current approved tool request */
  approvedToolGrant: Annotation<ShellGrantUsed | null>({
    reducer: (_left, right) => right,
    default: () => null,
  }),
  /** 当前批次中已审批工具的 Permit 映射 (call_id → permit)，tools 节点消费后清空 */
  approvedBatch: Annotation<PermitBatch>({
    reducer: (_left, right) => right,
    default: () => ({}),
  }),
  executionEnvironment: Annotation<'local_unsafe' | 'workspace_sandbox'>({
    reducer: (_left, right) => right,
    default: () => 'local_unsafe',
  }),
  sandboxBackend: Annotation<SandboxBackend | 'unknown'>({
    reducer: (_left, right) => right,
    default: () => 'unknown',
  }),
  interactionMode: Annotation<InteractionMode>({
    reducer: (_left, right) => right,
    default: () => 'ask',
  }),
  executionJournal: Annotation<ExecutionJournalEntry[]>({
    reducer: (_left, right) => right,
    default: () => [],
  }),
  exhaustedFingerprints: Annotation<Record<string, true>>({
    reducer: (_left, right) => right,
    default: () => ({}),
  }),
  pendingSubagentApproval: Annotation<PendingSubAgentApproval | null>({
    reducer: (_left, right) => right,
    default: () => null,
  }),
  /** 当前 thread 的 shell 授权状态 / Shell authorization state scoped to the current thread */
  authorization: Annotation<ThreadAuthorizationState>({
    reducer: (_left, right) => right,
    default: defaultAuthorizationState,
  }),
  /** 持久化的执行计划 / Persisted execution plan */
  plan: Annotation<AgentPlan | null>({
    reducer: (_left, right) => right,
    default: () => null,
  }),
  /** 当前 session 中是否已有方案通过用户审批（首个方案审批后设为 true，后续不重置）。
   *  plan_review 审批通过后设为 true，tools 节点产出 plan（纯进度更新）时保持不变。
   *  Whether a plan has been approved by the user in this session. Set to true after first plan_review approval; never reset.
   *  Tools node's progress-only update_plan keeps this flag unchanged. */
  planReviewed: Annotation<boolean>({
    reducer: (_left, right) => right,
    default: () => false,
  }),
  /** 上下文预算配置 / Context budget configuration */
  contextBudget: Annotation<ContextBudget | undefined>({
    reducer: (_left, right) => right,
    default: () => undefined,
  }),
  /** 模型提供商 / Model provider (e.g. openai, deepseek, anthropic) */
  modelProvider: Annotation<string>({
    reducer: (_left, right) => right,
    default: () => '',
  }),
  /** 模型名称 / Model name (e.g. gpt-4o, deepseek-v3) */
  modelName: Annotation<string>({
    reducer: (_left, right) => right,
    default: () => '',
  }),
  /** 思考级别 / Thinking level (null = default, "low", "medium", "high") */
  thinkingLevel: Annotation<string | null>({
    reducer: (_left, right) => right,
    default: () => null,
  }),
  /** 对话消息列表 / Conversation message list */
  messages: Annotation<BaseMessage[]>({
    reducer: messagesStateReducer,
    default: () => [],
  }),
  /** 最终回答文本 / Final answer text */
  final: Annotation<string>({
    reducer: (_left, right) => right,
    default: () => '',
  }),
  /** 当前激活的 Skill 关键指令（从 <EXTREMELY-IMPORTANT> 标签提取，注入 runtime context）/ Active skill critical instructions extracted from <EXTREMELY-IMPORTANT> tags */
  activeSkillInstructions: Annotation<string>({
    reducer: (_left, right) => right,
    default: () => '',
  }),
  /** Auto-review 持久化状态（待注入警告 + 连续拒绝计数 + 拒绝历史 + 断路器状态）/
   *  Persistent auto-review state (pending warnings + consecutive rejects + rejection history + breaker status) */
  autoReviewState: Annotation<AutoReviewState>({
    reducer: (_left, right) => right,
    default: () => DEFAULT_AUTO_REVIEW_STATE,
  }),
  /** doom-loop 重复调用追踪 / Doom-loop repeat call tracker */
  doomLoopTracker: Annotation<Record<string, { count: number; lastSeenAt: number }>>({
    reducer: (_left, right) => right,
    default: () => ({}),
  }),
});

export type CodeAgentState = typeof AgentState.State;
