import { platform, release, type } from "node:os";
import type { BaseMessage } from "@langchain/core/messages";
import type { AgentEvidence, AgentMode, AgentPlan, AgentProgressLedger } from "../shared/types";

/** 运行时系统信息 / Runtime system information */
export interface RuntimeSystemInfo {
  /** 当前时间 ISO 格式 / Current time in ISO format */
  currentTimeIso: string;
  /** 时区 / Timezone */
  timezone: string;
  /** 操作系统类型 / OS type */
  os: string;
  /** 平台 / Platform */
  platform: string;
  /** 系统版本 / OS release version */
  release: string;
  /** 当前 Shell / Current shell */
  shell: string;
  /** 当前工作目录 / Current working directory */
  cwd: string;
  /** 工作区路径 / Workspace path */
  workspace: string;
}

/** 运行时上下文输入参数 / Runtime context input parameters */
export interface RuntimeContextInput {
  /** 用户 ID / User ID */
  userId: string;
  /** 工作目录 / Workspace path */
  workspace: string;
  /** 模型名称 / Model name */
  modelName?: string;
  /** 对话消息 / Conversation messages */
  messages: BaseMessage[];
  /** 运行模式 / Run mode */
  mode?: AgentMode;
  /** 执行计划 / Execution plan */
  plan?: AgentPlan | null;
  /** 上下文摘要 / Context summary */
  contextSummary?: string;
  /** 执行证据 / Execution evidence */
  evidence?: AgentEvidence;
  /** 进度跟踪 / Progress tracking */
  progress?: AgentProgressLedger;
  /** 可注入的当前时间 / Injectable current time */
  now?: Date;
  /** 可注入的时区 / Injectable timezone */
  timezone?: string;
}

/** 收集运行时系统信息 / Collect runtime system information */
export function getRuntimeSystemInfo(input: {
  workspace: string;
  now?: Date;
  timezone?: string;
}): RuntimeSystemInfo {
  const now = input.now ?? new Date();
  return {
    currentTimeIso: now.toISOString(),
    timezone: input.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone,
    os: type(),
    platform: platform(),
    release: release(),
    shell: process.env.SHELL || process.env.ComSpec || "powershell",
    cwd: process.cwd(),
    workspace: input.workspace,
  };
}

/** 构建动态运行时上下文（含时间戳，不适合缓存）/ Build dynamic runtime context (includes timestamps, not cacheable) */
export function buildRuntimeContext(input: RuntimeContextInput): string {
  const info = getRuntimeSystemInfo(input);
  const mode = input.mode ?? "builder";
  const lines = [
    "Dynamic runtime context:",
    `Time: ${info.currentTimeIso}`,
    `Timezone: ${info.timezone}`,
    `OS: ${info.os} ${info.release} (${info.platform})`,
    `Shell: ${info.shell}`,
    `CWD: ${info.cwd}`,
    `Workspace: ${info.workspace}`,
    `User ID: ${input.userId}`,
    ...(input.modelName ? [`Configured model: ${input.modelName}`] : []),
    `Thread mode: ${mode}`,
    `Tool policy: ${toolPolicy(mode)}`,
  ];

  return lines.join("\n");
}

/** 构建可缓存的运行时上下文（不含时间戳，适合 DeepSeek 前缀缓存）/ Build cacheable runtime context (no timestamps, cache-stable for DeepSeek prefix cache) */
export function buildCacheableRuntimeContext(input: RuntimeContextInput): string {
  const mode = input.mode ?? "builder";
  const lines = [
    "Cacheable runtime context:",
    `Workspace: ${input.workspace}`,
    `User ID: ${input.userId}`,
    ...(input.modelName ? [`Configured model: ${input.modelName}`] : []),
    `Thread mode: ${mode}`,
    `Tool policy: ${toolPolicy(mode)}`,
  ];

  return lines.join("\n");
}

/** 将计划格式化为运行时状态提醒文本 / Format plan as runtime state reminder text */
export function formatPlanStateReminder(plan: NonNullable<RuntimeContextInput["plan"]>): string {
  const lines = [
    '<runtime-state source="graph.state.plan">',
    "This message is generated by the harness, not by the user.",
    "Use it as the current persisted plan state.",
    `Name: ${plan.name}`,
    `Status: ${plan.status}`,
    `Description: ${plan.description}`,
    "Steps:",
    ...plan.steps.map((step) => `- [${step.status}] ${step.step}`),
    "</runtime-state>",
  ];
  return lines.join("\n");
}

/** 根据模式返回工具策略描述 / Return tool policy description based on mode */
function toolPolicy(mode: AgentMode): string {
  if (mode === "plan") {
    return "read-only planning; may read files/search/list/git inspect through shell_read and update_plan; must not write, delete, run tests, install dependencies, execute project code, or mutate workspace";
  }
  // builder 模式：写/删/执行工具需要审批 / builder mode: write/delete/execute tools require approval
  return "execute mode; write/delete/execute tools require approval before running";
}
