import type { ProfileAccess } from '../../platform/profile';
import type { SqliteEngineSelection } from '../../sqlite-engine';
import type { Store } from '../port';
export type StoreCall = {
  [K in Exclude<keyof Store, 'close'>]: { id: number; method: K; args: Parameters<Store[K]> };
}[Exclude<keyof Store, 'close'>];
export type WorkerRequest =
  | StoreCall
  | {
      id: number;
      method: 'open';
      args: [
        {
          access: Omit<ProfileAccess, 'lock'>;
          readOnly: boolean;
          engine: SqliteEngineSelection | null;
        },
      ];
    }
  | { id: number; method: 'getRecoveryReceipt'; args: Parameters<Store['recoverSession']> }
  | { id: number; method: 'close'; args: [] };
export const storeMethods: readonly (keyof Store)[] = [
  'getMetadata',
  'readRunExecutionSafety',
  'readExecutionGroupSafety',
  'verifyRunResume',
  'beginRunResume',
  'commitRunResume',
  'releaseRunResumeLease',
  'beginRunRequirementsInitialization',
  'beginSessionExport',
  'readSessionExportText',
  'readSessionExportPage',
  'verifySessionExport',
  'createWorkspace',
  'getWorkspace',
  'listWorkspaces',
  'listWorkspaceDirectory',
  'listSessionDirectory',
  'listBackgroundExecutions',
  'createSession',
  'getSession',
  'listSessions',
  'acceptCommand',
  'getCommand',
  'listAcceptedCommands',
  'rejectCommand',
  'acquireSessionOwner',
  'releaseSessionOwner',
  'inspectOwnerDispatch',
  'startRun',
  'registerRunRequirements',
  'registerMutationIntent',
  'listMutationFacts',
  'commitMutationCheck',
  'initializeRunRecord',
  'getRun',
  'planExecution',
  'activateChildRun',
  'acceptAgentInput',
  'queueAgentMessage',
  'readAgentMessageTarget',
  'receiveAgentMessages',
  'getAgentMessage',
  'listAgentMessages',
  'interruptAgent',
  'getAgentSummary',
  'listAgentSummaries',
  'ensureAgentFollowUp',
  'markDispatching',
  'markRunning',
  'appendExecutionOutput',
  'listExecutionOutput',
  'finishExecution',
  'sealJobRecoveryManifest',
  'getJobReconciliationReceipt',
  'beginJobReconciliation',
  'markJobReconciliationDispatch',
  'finishJobReconciliation',
  'releaseJobRecoveryLease',
  'applyJobReport',
  'verifyJobReportRecovery',
  'listPendingJobReports',
  'getExecution',
  'getModelOutputSnapshot',
  'getModelInputSnapshot',
  'listModelInputs',
  'listExecutions',
  'persistModelPartial',
  'listMessages',
  'getView',
  'getExtensionRecord',
  'listExtensionRecords',
  'writeExtensionRecord',
  'ensureAuthorizationReview',
  'getAuthorizationReview',
  'ensureOperation',
  'getOperation',
  'planAction',
  'applyExtensionAction',
  'stopActionPreparation',
  'recoverSession',
  'readRecoveryToolHistory',
  'finishRun',
  'setRunResultWait',
  'cancelCommand',
  'cancelWork',
  'getChanges',
  'getSessionLogs',
  'registerArtifact',
  'getArtifactReference',
  'beginHostMutation',
  'finishHostMutation',
  'getHostMutation',
  'readHostControl',
  'getPermissionGrant',
  'listPermissionGrants',
  'clearPermissionGrants',
  'requestInteraction',
  'answerInteraction',
  'acceptInteractionDecision',
  'getInteraction',
  'listInteractions',
  'applyInput',
  'listPendingInputs',
  'selectContext',
  'forkSession',
  'readForkNamespacePage',
  'renameSession',
  'deleteSession',
  'getMessageOrigin',
  'readForkRecordSources',
  'prepareForkReadonlySources',
  'readForkSourceProjection',
  'readForkSourceMessage',
  'consumeJobResult',
  'includeResult',
  'getSelectedContext',
  'readOriginalRunSelection',
  'getCompressionOrigin',
  'beginCompression',
  'commitCompression',
  'resetCompression',
  'getExpandedContext',
  'getModelContext',
  'listPendingJobResults',
  'close',
];
