import { Text, type TextProps } from 'ink';
import { createContext, useContext, useMemo } from 'react';
import { defaultTuiPreferences } from './preferences';

/** Only explicit UI-owned labels enter this catalog. Public machine values and body text do not. */
export const tuiChinese: Readonly<Record<string, string>> = {
  Question: '问题',
  Answer: '回答',
  'Custom answer': '自定义回答',
  'Tab: skip optional answer': 'Tab：跳过可选回答',
  'No selection (Enter has no answer)': '尚未选择（Enter 不提交回答）',
  'Up/Down: choose · Enter: next/submit · Shift+Enter: newline · Esc: previous question':
    '上下键：选择 · Enter：下一题或提交 · Shift+Enter：换行 · Esc：上一题',
  'Answer needs at least': '回答至少需要',
  'Answer allows at most': '回答最多允许',
  characters: '个字符',
  entered: '已输入',
  'Ctrl+A: read required attachment. Question: choose or enter the original-schema answer above.':
    'Ctrl+A：读取必要附件。问题：选择或输入上方原 schema 的回答。',
  Authentication: '认证',
  'Original authentication requests': '原认证申请',
  'MCP authentication': 'MCP 认证',
  'Authentication does not reconnect or replay tools.': '认证不会重连或重放工具。',
  'Credential store:': '凭据后端：',
  'Credentials present': '已有凭据',
  'No credentials': '没有凭据',
  Login: '登录',
  'Refresh credentials': '刷新凭据',
  'Clear local credentials': '清理本地凭据',
  'Revoke remote credentials': '撤销远端凭据',
  Review: '审查',
  'Original authentication:': '原认证申请：',
  'Check original authentication': '查询原认证申请',
  'Cancel original authentication': '取消原认证申请',
  'Confirm authentication:': '确认认证操作：',
  'Enter submits this request; Esc abandons.': 'Enter 提交此申请；Esc 放弃。',
  'Reading authentication': '读取认证状态中',
  'Authentication pending': '认证申请待决',
  'Credentials saved; reconnect separately': '凭据已保存；请另行申请重连',
  'Remote revocation not supported; credentials retained': '远端不支持撤销；凭据已保留',
  'Credentials cleared': '凭据已清理',
  'Authentication failed': '认证失败',
  'Authentication cancelled': '认证已取消',
  'Authentication outcome unknown; check original': '认证结果未知；请查询原申请',
  'Authentication unavailable': '认证不可用',
  'Project sources': '项目来源',
  'Review project source': '审查项目来源',
  'Check original source decision': '查询原来源决定',
  'Original source decision:': '原来源决定申请：',
  'Source entry changes': '来源条目增删',
  'Add source entry': '新增来源条目',
  'Remove source entry:': '删除来源条目：',
  'Original source change:': '原来源修改申请：',
  'Check original source change': '查询原来源修改',
  'Removal clears owned OAuth credentials locally; shared credentials are retained. Connection status is separate.':
    '删除时本地清理自有 OAuth 凭据；保留共享凭据。连接状态需另行核实。',
  'Credential cleanup:': '凭据清理：',
  'Credential cleanup not attempted': '尚未尝试清理凭据',
  'No owned OAuth credentials to clear': '没有需要清理的自有 OAuth 凭据',
  'Owned OAuth credentials cleared': '已清理自有 OAuth 凭据',
  'Source removed; credential cleanup failed': '来源已删除；凭据清理失败',
  'Source removed; credential cleanup unknown': '来源已删除；凭据清理结果未知',
  'Source entry name': '来源条目名称',
  'Source entry value': '来源条目内容',
  'Current project': '当前项目',
  'All projects': '全部项目',
  'Review source entry change': '审查来源条目修改',
  'Confirm source entry change': '确认来源条目修改',
  'Enter continues; no configuration is submitted.': 'Enter 继续；此步不提交配置。',
  'Enter opens independent confirmation.': 'Enter 进入独立确认。',
  'Enter submits a new ordinary request; approval is separate.':
    'Enter 提交新的普通申请；执行许可仍需独立审批。',
  'Invalid source entry name': '来源条目名称无效',
  'Invalid source entry value': '来源条目内容无效',
  'Source entry input exceeds limit': '来源条目输入超出限额',
  'Source directory unavailable': '来源目录不可用',
  'Source removal preview unavailable': '来源删除预览不可用',
  'Reading source entry facts': '读取来源条目中',
  'Source mutation intent capacity reached': '来源修改申请已达限额',
  'Original source mutation unavailable': '原来源修改结果不可用',
  'Source mutation unavailable; check original before retry':
    '来源修改不可用；再次申请前请查询原结果',
  'Removal reveals user source:': '删除后显露用户来源：',
  'Removal reveals no fallback source.': '删除后没有显露的用户来源。',
  '↑/↓ scroll · Home/End · Enter continues · Esc back':
    '↑/↓ 滚动 · Home/End 跳转 · Enter 继续 · Esc 返回',
  'Original Store:': '原 Store：',
  'Refresh project sources': '刷新项目来源',
  'Next project sources': '下一页项目来源',
  'Previous project sources': '上一页项目来源',
  'Return to pending requests': '返回待决请求',
  'Confirm project source review:': '确认项目来源审查：',
  'Enter requests review; Esc abandons. Answer the original Question separately.':
    'Enter 申请审查；Esc 放弃。请另行回答原 Question。',
  'Review requests an independent decision; it does not connect or authorize tools.':
    '审查申请需要独立决定；不连接或授予工具权限。',
  'Source list ready': '来源列表已就绪',
  'Reading project sources': '读取项目来源中',
  'Source list unknown; original decisions remain available': '来源列表未知；原决定申请仍可选择',
  'No project sources in this observation': '本次观察没有项目来源',
  'Reading original source decision': '读取原来源决定中',
  'Source approval saved': '来源批准已保存',
  'Source rejection saved': '来源拒绝已保存',
  'Source outcome unknown; check original': '来源结果未知；查询原申请',
  'Waiting for original source decision': '等待原来源决定',
  'Source request failed': '来源申请失败',
  'Source request cancelled': '来源申请已取消',
  'Up/Down explicit source decision:': '上下键明确选择来源决定：',
  approved: '批准',
  rejected: '拒绝',
  cancel: '取消决定',
  admitted: '已准入',
  'not admitted': '未准入',
  'Selection applies to later work; active work and connections retain their configuration.':
    '选择用于后续任务；活动任务和连接保持原配置。',
  'Reading this list does not connect or authorize tools.':
    '读取列表不连接 Server，也不授予工具权限。',
  'Reading servers': '读取 Server 中',
  'Server list unknown; refresh to verify': 'Server 列表未知；刷新核实',
  'No configured MCP servers': '没有配置 MCP Server',
  'Server:': 'Server：',
  'Source:': '来源：',
  Enable: '启用',
  Disable: '禁用',
  'User settings': '用户设置',
  'Project settings': '项目设置',
  'Refresh servers': '刷新 Server',
  'Check original change': '核实原修改',
  Back: '返回',
  '↑/↓ choose · Enter select · Esc back': '↑/↓ 选择 · Enter 确认 · Esc 返回',
  'Confirm server change:': '确认 Server 修改：',
  'Enter saves; Esc abandons': 'Enter 保存；Esc 放弃',
  'Original change:': '原修改：',
  'Original connection:': '原连接申请：',
  'Request connection': '申请连接',
  'Check original connection': '查询原连接申请',
  'Saved tool snapshots': '保存的工具快照',
  'Server list ready': 'Server 列表已就绪',
  'Forced reconnects': '强制重连记录',
  'Original forced reconnect:': '原强制重连：',
  'Check original forced reconnect': '查询原强制重连',
  'Review forced reconnect': '审查强制重连',
  'Confirm forced reconnect': '确认强制重连',
  'Confirm forced reconnect:': '确认强制重连：',
  'Selecting an original ID does not query, reconnect or authorize tools.':
    '选择原 ID 不会查询、重连或授予工具权限。',
  'Reading current reconnect target': '正在读取当前重连目标',
  'Original carrier:': '原载体：',
  'Replacement source:': '替换来源：',
  'Static registration': '静态注册',
  'Project Source': '项目来源',
  'User Source': '用户来源',
  'Replacement transport:': '替换传输：',
  'Stopping the connection does not confirm remote Tool work stopped.':
    '连接停止不代表远端 Tool 工作已停止。',
  'Replacement configuration digest:': '替换配置摘要：',
  'Source name:': '来源名称：',
  'Enter submits a new independently approved request. The old connection may stop before replacement succeeds; no automatic restore or tool permission.':
    'Enter 提交需要独立审批的新申请。替换成功前原连接可能已停止；不会自动恢复，也不授予工具权限。',
  'Reading original forced reconnect': '正在读取原强制重连',
  'Replacement catalogue ready': '替换目录已就绪',
  'Forced reconnect failed': '强制重连失败',
  'Forced reconnect cancelled': '强制重连已取消',
  'Waiting for original forced reconnect': '等待原强制重连',
  'Forced reconnect outcome unknown; Check original': '强制重连结果未知；请查询原申请',
  'Original connection stop confirmed': '原连接停止已确认',
  'Original connection stop unknown': '原连接是否停止未知',
  'Live replacement observed': '已观察到活动替换连接',
  'Live replacement not confirmed': '活动替换连接未确认',
  'Confirm connection request:': '确认连接申请：',
  'Enter requests connection; Esc abandons. Independent approval required; no tool permission granted.':
    'Enter 申请连接；Esc 放弃。仍需独立审批，不授予工具权限。',
  'Reading original connection': '读取原连接申请中',
  'Original catalogue ready': '原目录已就绪',
  'Waiting for original connection': '等待原连接申请结果',
  'Connection request failed': '连接申请失败',
  'Connection outcome unknown; check original': '连接结果未知；查询原申请',
  'Live connection observed': '已观察到当前连接',
  'Live connection not confirmed': '当前连接尚未确认',
  'Created by original request': '由原申请新建',
  'Reused original connection': '复用了原连接',
  'Creation unknown': '新建状态未知',
  'current generation': '当前代次',
  Generation: '代次',
  tools: '个工具',
  '[name preview]': '[名称预览]',
  'Next saved snapshots': '下一页保存的快照',
  'Next tools': '下一页工具',
  'Previous tools': '上一页工具',
  'Retry read': '重试读取',
  'MCP Tools · saved metadata': 'MCP 工具 · 保存的描述',
  'Reading does not connect or authorize tools.': '读取不连接 Server，也不授予工具权限。',
  'original generation': '原代次',
  'Historical snapshot': '历史快照',
  'Reading original metadata · incomplete': '读取原工具描述中 · 尚未完整',
  'Metadata unavailable': '工具描述不可用',
  Tools: '工具',
  'last index page': '索引末页',
  'more pages': '还有后续页',
  'Complete metadata · EOF and hash verified': '完整工具描述 · 已核实 EOF 与摘要',
  'outputSchema: absent': 'outputSchema：未提供',
  Rows: '行',
  '↑/↓ scroll · ←/→ page · Home/End · Esc back': '↑/↓ 滚动 · ←/→ 翻页 · Home/End · Esc 返回',
  '↑/↓ choose · Enter read · Esc back': '↑/↓ 选择 · Enter 读取 · Esc 返回',
  'Selection saved': '选择已保存',
  'Selection failed': '选择保存失败',
  'Waiting for original result': '等待原执行结果',
  'Outcome unknown; check original change': '结果未知；核实原修改',
  Session: '会话',
  'Select Session (arrows/Enter, Esc)': '选择会话（方向键/Enter，Esc）',
  'Recorded Model output preview only;': '仅为已记录的 Model 输出预览；',
  'bytes,': '字节，',
  '] original Session': '] 原会话',
  '· revision': '· 修订',
  'Up/Down explicit approval selection:': '上下键明确选择批准范围：',
  'Ctrl+A: read required attachment. Approval: approve (once), approve same_command only if offered, deny. Question: original-schema JSON. Plan: approve offered mode / revise feedback / deny.':
    'Ctrl+A：读取所需附件。批准：approve（仅一次）、仅提供时可用 approve same_command、deny。问题：原 schema JSON。计划：approve 已提供模式 / revise 反馈 / deny。',
  Selection: '选择',
  '/ frozen upper': '/ 固定上界',
  Source: '来源',
  'Context reading/unavailable': '上下文读取中/不可用',
  'Choose exact historical result with arrows; i explicitly includes into displayed active original Run or idle selection.':
    '方向键选择准确历史结果；i 明确纳入所显示的原活动 Run 或空闲选择。',
  revision: '修订',
  'Target Run': '目标 Run',
  'Original management': '原管理操作',
  Original: '原操作',
  '(receipt is not dispatch success)': '（回执不代表派发成功）',
  'Ctrl+R sessions · Ctrl+L refresh · Ctrl+O full output · Ctrl+C cancels exact original Command':
    'Ctrl+R 会话 · Ctrl+L 刷新 · Ctrl+O 完整输出 · Ctrl+C 取消准确原 Command',
  '· Workspace': '· 工作区',
  'Saved project settings apply to later executions; active Run keeps its original model.':
    '保存的项目设置用于后续执行；活动 Run 保持原模型。',
  'Reading actual configured models': '读取实际配置模型',
  'Desired default:': '期望默认模型：',
  'Current effective effort:': '当前有效推理深度：',
  'Read only:': '只读：',
  'Adapter wire vocabulary only; actual provider may reject unsupported effort.':
    '仅为适配器协议选项；实际 Provider 可能拒绝不支持的深度。',
  'Reasoning effort unavailable for this model': '该模型推理深度不可用',
  'No configured models; unavailable': '没有配置模型；不可用',
  '· R read · K original outcome · Esc close': '· R 读取 · K 核实原结果 · Esc 关闭',
  'Confirm original project change': '确认原项目修改',
  '; Enter save / Esc abandon': '；Enter 保存 / Esc 放弃',
  'Permissions · original Session': '权限 · 原会话',
  'Reading actual permission controls': '读取实际权限控制',
  Mode: '模式',
  '· scope': '· 范围',
  '· default': '· 默认',
  'Future Session default:': '以后会话默认值：',
  '· D toggle · Enter review mode choice': '· D 切换 · Enter 核对模式选择',
  Workspace: '工作区',
  ', revision': '，修订',
  Identity: '身份',
  '· read scope': '· 读取范围',
  'T review trust / U review untrust · trust does not approve every Tool':
    'T 核对信任 / U 核对撤销信任 · 信任不代表批准所有 Tool',
  'Saved same_command grants:': '已保存 same_command 授权：',
  '· frozen upper': '· 固定上界',
  'C review clear this exact Session only; earlier effects remain · R refresh · K original outcome lookup · Esc close':
    'C 核对清除此准确会话；已有影响保留 · R 刷新 · K 查询原结果 · Esc 关闭',
  'Confirm original': '确认原操作',
  '· Enter explicitly submits · Esc leaves unchanged': '· Enter 明确提交 · Esc 保持不变',
  'Original permission': '原权限操作',
  '(control saved is not dispatch success)': '（控制保存不代表派发成功）',
  'Host status · Esc back · R refresh': '宿主状态 · Esc 返回 · R 刷新',
  'Connection:': '连接：',
  '· Profile:': '· Profile：',
  'Observation:': '持续观察：',
  '· Session snapshot:': '· 会话快照：',
  'Build:': '构建：',
  '· API:': '· API：',
  'Instance:': '实例：',
  'Store:': 'Store：',
  '· Data:': '· 数据：',
  'Workspace:': '工作区：',
  '· Session:': '· 会话：',
  'Execution host:': '执行宿主：',
  '· Last Session snapshot:': '· 最后会话快照：',
  'Active Run:': '活动 Run：',
  'Unsettled execution:': '未结算执行：',
  'Sandbox:': '沙箱：',
  'Shell:': 'Shell：',
  'Permissions:': '权限：',
  '· Trust:': '· 信任：',
  'Release:': '发行：',
  'Telemetry: disabled ·': '遥测：禁用 ·',
  'No confirmed host facts': '无已确认宿主事实',
  'Current host status unknown; refresh to verify original host':
    '当前宿主状态未知；刷新核实原宿主',
  'Knowledge Skills · total': '知识 Skills · 总数',
  'Workflow:': 'Workflow：',
  'Manual:': '手动激活：',
  'Input {}:': '输入 {}：',
  'Workflow version:': 'Workflow 版本：',
  'Read only · Use /name [task] in the composer': '只读 · 在输入框使用 /name [任务]',
  'Read only · Workflow activation is not available here': '只读 · 此处不提供 Workflow 激活',
  'Discovery does not grant tool permissions': '发现目录不授予工具权限',
  'Catalog read:': '目录读取：',
  '· Observation:': '· 持续观察：',
  '↑/↓ entries · ←/→ details · R refresh · Esc back': '↑/↓ 条目 · ←/→ 详情 · R 刷新 · Esc 返回',
  'Revision:': '修订：',
  Entry: '条目',
  'Details page': '详情页',
  'Current catalogue unknown:': '当前目录未知：',
  '; refresh original Workspace': '；刷新原工作区',
  '[image:': '[图片：',
  'Quote:': '引用：',
  'not selected': '未选择',
  ' · Loading': ' · 加载中',
  ' · Stale': ' · 观察失联',
  'full read unsupported': '不支持完整读取',
  'Ctrl+O reads verified full body': 'Ctrl+O 读取已验证完整正文',
  'full reader unavailable': '完整读取器不可用',
  complete: '完整',
  'incomplete prefix': '不完整前缀',
  'none (Enter has no answer)': '未选择（Enter 不提交答案）',
  'only this call': '仅此次调用',
  'same command in original Session': '原会话相同命令',
  deny: '拒绝',
  'Idle Rewind: choose original boundary with arrows/Enter; 0 empty; Esc close':
    '空闲回退：方向键/Enter 选择原边界；0 空边界；Esc 关闭',
  'Current selected Context projection, not actual Model input Inspector; Esc close':
    '当前选中上下文投影，并非实际 Model 输入检查器；Esc 关闭',
  '(stop unconfirmed; files unchanged)': '（停止未确认；文件未改动）',
  '(receipt queued, not completed)': '（回执已排队，未完成）',
  ' · Fork omitted extension state': ' · Fork 省略扩展状态',
  'Queue follow-up after original maintenance Run': '在原维护 Run 后排队后继输入',
  'Steer original active Run': '引导原活动 Run',
  'New Run': '新 Run',
  'Reasoning effort': '推理深度',
  Models: '模型',
  none: '无',
  unavailable: '不可用',
  unspecified: '未指定',
  'stale / read only': '观察失联 / 只读',
  available: '可用',
  'clear project effort (read resulting value)': '清除项目深度（重读最终值）',
  enabled: '启用',
  disabled: '禁用',
  configured: '已配置',
  incomplete: '配置不完整',
  '↑↓ choose effort · Enter review effort': '↑↓ 选择深度 · Enter 核对深度',
  '↑↓ select exact ID · Enter review default · E review enabled':
    '↑↓ 选择准确 ID · Enter 核对默认值 · E 核对启用状态',
  yes: '是',
  no: '否',
  'Confirmed host facts': '已确认宿主事实',
  'Last confirmed host facts (current unknown)': '最后已确认宿主事实（当前未知）',
  'none in snapshot': '快照中没有',
  'Last confirmed catalogue (current unknown)': '最后已确认目录（当前未知）',
  'No configured Skill entries': '没有配置 Skill 条目',
  'Catalogue source unavailable': '目录来源不可用',
  'No confirmed catalogue': '无已确认目录',
  'Name:': '名称：',
  'ID:': 'ID：',
  'State:': '状态：',
  '· Reason:': '· 原因：',
  'Version:': '版本：',
  'Required capabilities:': '所需能力：',
  'Missing capabilities:': '缺少能力：',
  'Description:': '描述：',
  'Catalogue:': '目录：',
  Unavailable: '不可用',
  'Unknown — verify original work': '未知 — 核实原任务',
  Cancelling: '取消中',
  'Waiting for answer': '等待回答',
  'Waiting for required result': '等待所需结果',
  Working: '工作中',
  Idle: '空闲',
  'Confirmed preferences': '已确认偏好',
  'Effective language:': '生效语言：',
  'Base theme:': '基础主题：',
  'Error:': '错误：',
  'Notice:': '提示：',
  'Exported loaded conversation:': '已导出加载的对话：',
  'Export failed': '导出失败',
  'Export failed: loaded conversation unavailable': '导出失败：已加载对话不可用',
  'Local draft save failed; showing durable disk versions only':
    '本机草稿保存失败；仅显示已落盘版本',
  'No saved drafts': '无已保存草稿',
  ' · Store ': ' · Store ',
  ' · Workspace ': ' · 工作区 ',
  ' · Session ': ' · 会话 ',
  ' · revision ': ' · 修订 ',
  'Original draft ': '原草稿 ',
  ' · association ': ' · 关联 ',
  Theme: '主题',
  Language: '语言',
  'Local client preferences; work and permissions remain unchanged.':
    '本机客户端偏好；任务与权限保持不变。',
  '↑↓ select · Enter save · R reread · Esc back': '↑↓ 选择 · Enter 保存 · R 重读 · Esc 返回',
  'Save outcome unknown; last confirmed values retained. R rereads original preferences before another choice.':
    '保存结果未知；保留最后确认值。R 读取原偏好后才能再次选择。',
  'Preference saved': '偏好已保存',
  'Reading preferences': '读取偏好中',
  'Saving preference': '保存偏好中',
  'Preference failed; previous values retained. R rereads before another choice.':
    '偏好操作失败；保留原值。R 重读后才能再次选择。',
  'System language': '系统语言',
  'Simplified Chinese': '简体中文',
  English: '英文',
};
export type TuiTranslator = (label: string) => string;
const Presentation = createContext({ preferences: defaultTuiPreferences });
export const TuiPresentationProvider = Presentation.Provider;
export function useTuiPresentation() {
  const { preferences } = useContext(Presentation);
  const t = useMemo<TuiTranslator>(
    () => (label) =>
      preferences.resolvedLanguage === 'zh-CN' ? (tuiChinese[label] ?? label) : label,
    [preferences.resolvedLanguage],
  );
  return { t, preferences };
}
const lightAccents = {
  teal: '#087E66',
  blue: '#1B5894',
  purple: '#713795',
  cyan: '#086C85',
  mono: '#404040',
};
const accents = {
  teal: '#4EC9B0',
  blue: '#569CD6',
  purple: '#C586C0',
  cyan: '#11A8CD',
  mono: '#C0C0C0',
};
export function TuiText(props: TextProps) {
  const { preferences } = useTuiPresentation();
  const dark = preferences.theme === 'dark';
  const color =
    props.color === 'red'
      ? dark
        ? '#FF7373'
        : '#A00000'
      : props.color === 'yellow'
        ? dark
          ? '#E4CA5A'
          : '#765B00'
        : (props.color ??
          (props.bold
            ? (dark ? accents : lightAccents)[preferences.colorPreset]
            : dark
              ? '#D4D4D4'
              : '#202020'));
  return <Text {...props} color={color} />;
}
