/** Store 11 additions. These statements run only on a fresh Store or a private migration candidate. */
export const KITE_SESSION_AGENT_TABLE_COLUMNS = Object.freeze({
  agent_nodes: [
    'session_id',
    'agent_id',
    'parent_agent_id',
    'current_task_id',
    'current_submission_id',
    'current_owner_generation',
    'current_grant_digest',
    'status',
    'turn_ordinal',
    'prepared_through_sequence',
    'latest_checkpoint_artifact_id',
    'latest_checkpoint_integrity_identifier',
    'latest_checkpoint_byte_length',
    'created_at_ms',
  ],
  agent_mail_bodies: [
    'session_id',
    'body_id',
    'integrity_identifier',
    'byte_length',
    'body_text',
    'created_at_ms',
  ],
  agent_mail: [
    'session_id',
    'message_id',
    'submission_id',
    'sequence',
    'sender_agent_id',
    'target_agent_id',
    'recipient_run_id',
    'mode',
    'source_run_id',
    'source_turn_id',
    'source_model_invocation_id',
    'source_tool_call_id',
    'source_effect_attempt_id',
    'source_task_id',
    'request_digest',
    'body_id',
    'followup_admission_artifact_id',
    'followup_admission_digest',
    'status',
    'prepared_invocation_id',
    'model_admission_id',
    'accepted_at_ms',
  ],
  agent_mail_outbox: [
    'source_session_id',
    'message_id',
    'target_session_id',
    'target_run_id',
    'command_id',
    'request_digest',
    'source_run_id',
    'source_turn_id',
    'source_model_invocation_id',
    'source_tool_call_id',
    'source_effect_attempt_id',
    'source_task_id',
    'source_grant_id',
    'source_grant_digest',
    'mode',
    'body_id',
    'source_sequence',
    'source_revision',
    'accepted_at_ms',
    'delivered_target_revision',
  ],
  agent_mail_inbox: [
    'target_session_id',
    'message_id',
    'source_session_id',
    'target_run_id',
    'sequence',
    'target_revision',
    'received_at_ms',
    'prepared_invocation_id',
    'prepared_model_admission_id',
  ],
  subagent_checkpoint_artifacts: [
    'artifact_id',
    'integrity_identifier',
    'artifact_format_version',
    'canonical_json',
    'byte_length',
    'created_at',
  ],
  agent_followup_admission_artifacts: [
    'artifact_id',
    'integrity_identifier',
    'artifact_format_version',
    'canonical_json',
    'byte_length',
    'created_at',
  ],
} as const);

export const KITE_SESSION_AGENT_DDL = Object.freeze([
  `CREATE TABLE agent_nodes (
    session_id TEXT NOT NULL REFERENCES runtime_sessions(session_id) ON DELETE CASCADE,
    agent_id TEXT NOT NULL,
    parent_agent_id TEXT,
    current_task_id TEXT,
    current_submission_id TEXT,
    current_owner_generation TEXT,
    current_grant_digest TEXT,
    status TEXT NOT NULL CHECK (status IN ('idle','active','context_unavailable')),
    turn_ordinal INTEGER NOT NULL DEFAULT 0 CHECK (turn_ordinal >= 0),
    prepared_through_sequence INTEGER NOT NULL DEFAULT 0 CHECK (prepared_through_sequence >= 0),
    latest_checkpoint_artifact_id TEXT REFERENCES subagent_checkpoint_artifacts(artifact_id),
    latest_checkpoint_integrity_identifier TEXT,
    latest_checkpoint_byte_length INTEGER,
    created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
    PRIMARY KEY (session_id, agent_id),
    FOREIGN KEY (session_id, parent_agent_id) REFERENCES agent_nodes(session_id, agent_id),
    CHECK ((current_owner_generation IS NULL) = (current_grant_digest IS NULL)),
    CHECK ((latest_checkpoint_artifact_id IS NULL) = (latest_checkpoint_integrity_identifier IS NULL AND latest_checkpoint_byte_length IS NULL))
  ) STRICT`,
  `CREATE TABLE agent_mail_bodies (
    session_id TEXT NOT NULL REFERENCES runtime_sessions(session_id) ON DELETE CASCADE,
    body_id TEXT NOT NULL,
    integrity_identifier TEXT NOT NULL CHECK (length(integrity_identifier) = 71 AND substr(integrity_identifier, 1, 7) = 'sha256:'),
    byte_length INTEGER NOT NULL CHECK (byte_length BETWEEN 1 AND 4096),
    body_text TEXT NOT NULL,
    created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
    PRIMARY KEY (session_id, body_id),
    CHECK (length(CAST(body_text AS BLOB)) = byte_length)
  ) STRICT`,
  `CREATE TABLE agent_mail (
    session_id TEXT NOT NULL REFERENCES runtime_sessions(session_id) ON DELETE CASCADE,
    message_id TEXT NOT NULL,
    submission_id TEXT,
    sequence INTEGER NOT NULL CHECK (sequence > 0),
    sender_agent_id TEXT NOT NULL,
    target_agent_id TEXT NOT NULL,
    recipient_run_id TEXT,
    mode TEXT NOT NULL CHECK (mode IN ('queue_only','trigger_turn','reply')),
    source_run_id TEXT NOT NULL,
    source_turn_id TEXT NOT NULL,
    source_model_invocation_id TEXT NOT NULL,
    source_tool_call_id TEXT NOT NULL,
    source_effect_attempt_id TEXT NOT NULL,
    source_task_id TEXT,
    request_digest TEXT NOT NULL CHECK (length(request_digest) = 64),
    body_id TEXT NOT NULL,
    followup_admission_artifact_id TEXT REFERENCES agent_followup_admission_artifacts(artifact_id),
    followup_admission_digest TEXT,
    status TEXT NOT NULL CHECK (status IN ('queued','prepared','context_unavailable')),
    prepared_invocation_id TEXT,
    model_admission_id TEXT,
    accepted_at_ms INTEGER NOT NULL CHECK (accepted_at_ms >= 0),
    PRIMARY KEY (session_id, message_id),
    UNIQUE (session_id, sequence),
    UNIQUE (session_id, source_run_id, source_turn_id, source_model_invocation_id, source_tool_call_id, source_effect_attempt_id),
    FOREIGN KEY (session_id, sender_agent_id) REFERENCES agent_nodes(session_id, agent_id),
    FOREIGN KEY (session_id, target_agent_id) REFERENCES agent_nodes(session_id, agent_id),
    FOREIGN KEY (session_id, body_id) REFERENCES agent_mail_bodies(session_id, body_id),
    CHECK ((mode = 'trigger_turn') = (submission_id IS NOT NULL AND followup_admission_artifact_id IS NOT NULL AND followup_admission_digest IS NOT NULL)),
    CHECK ((status = 'prepared') = (prepared_invocation_id IS NOT NULL AND model_admission_id IS NOT NULL))
  ) STRICT`,
  `CREATE TABLE agent_mail_outbox (
    source_session_id TEXT NOT NULL REFERENCES runtime_sessions(session_id),
    message_id TEXT NOT NULL,
    target_session_id TEXT NOT NULL REFERENCES runtime_sessions(session_id),
    target_run_id TEXT,
    command_id TEXT NOT NULL,
    request_digest TEXT NOT NULL CHECK (length(request_digest) = 64),
    source_run_id TEXT NOT NULL,
    source_turn_id TEXT NOT NULL,
    source_model_invocation_id TEXT NOT NULL,
    source_tool_call_id TEXT NOT NULL,
    source_effect_attempt_id TEXT NOT NULL,
    source_task_id TEXT,
    source_grant_id TEXT,
    source_grant_digest TEXT,
    mode TEXT NOT NULL CHECK (mode IN ('queue_only','trigger_turn','reply')),
    body_id TEXT NOT NULL,
    source_sequence INTEGER NOT NULL CHECK (source_sequence >= 1),
    source_revision INTEGER NOT NULL CHECK (source_revision >= 1),
    accepted_at_ms INTEGER NOT NULL CHECK (accepted_at_ms >= 0),
    delivered_target_revision INTEGER CHECK (delivered_target_revision >= 1),
    PRIMARY KEY (source_session_id,message_id),
    UNIQUE (source_session_id,command_id),
    UNIQUE (source_session_id,source_sequence),
    FOREIGN KEY (source_session_id,body_id) REFERENCES agent_mail_bodies(session_id,body_id),
    CHECK (source_session_id <> target_session_id),
    CHECK ((source_grant_id IS NULL) = (source_grant_digest IS NULL))
  ) STRICT`,
  `CREATE TABLE agent_mail_inbox (
    target_session_id TEXT NOT NULL REFERENCES runtime_sessions(session_id),
    message_id TEXT NOT NULL,
    source_session_id TEXT NOT NULL REFERENCES runtime_sessions(session_id),
    target_run_id TEXT,
    sequence INTEGER NOT NULL CHECK (sequence >= 1),
    target_revision INTEGER NOT NULL CHECK (target_revision >= 1),
    received_at_ms INTEGER NOT NULL CHECK (received_at_ms >= 0),
    prepared_invocation_id TEXT,
    prepared_model_admission_id TEXT,
    PRIMARY KEY (target_session_id,message_id),
    UNIQUE (target_session_id,sequence),
    CHECK ((prepared_invocation_id IS NULL) = (prepared_model_admission_id IS NULL)),
    CHECK (source_session_id <> target_session_id)
  ) STRICT`,
  `CREATE TABLE subagent_checkpoint_artifacts (
    artifact_id TEXT PRIMARY KEY NOT NULL CHECK (length(artifact_id) = 67 AND substr(artifact_id, 1, 3) = 'pa_'),
    integrity_identifier TEXT NOT NULL UNIQUE CHECK (length(integrity_identifier) = 71 AND substr(integrity_identifier, 1, 7) = 'sha256:'),
    artifact_format_version INTEGER NOT NULL CHECK (artifact_format_version >= 1),
    canonical_json TEXT NOT NULL CHECK (json_valid(canonical_json)),
    byte_length INTEGER NOT NULL CHECK (byte_length BETWEEN 1 AND 16777216),
    created_at INTEGER NOT NULL CHECK (created_at >= 0)
  ) STRICT`,
  `CREATE TABLE agent_followup_admission_artifacts (
    artifact_id TEXT PRIMARY KEY NOT NULL CHECK (length(artifact_id) = 67 AND substr(artifact_id, 1, 3) = 'pa_'),
    integrity_identifier TEXT NOT NULL UNIQUE CHECK (length(integrity_identifier) = 71 AND substr(integrity_identifier, 1, 7) = 'sha256:'),
    artifact_format_version INTEGER NOT NULL CHECK (artifact_format_version >= 1),
    canonical_json TEXT NOT NULL CHECK (json_valid(canonical_json)),
    byte_length INTEGER NOT NULL CHECK (byte_length BETWEEN 1 AND 16777216),
    created_at INTEGER NOT NULL CHECK (created_at >= 0)
  ) STRICT`,
  'CREATE INDEX agent_mail_target_sequence ON agent_mail(session_id, target_agent_id, sequence)',
  'CREATE INDEX agent_nodes_parent ON agent_nodes(session_id, parent_agent_id)',
  'CREATE INDEX agent_mail_outbox_pending ON agent_mail_outbox(source_session_id,message_id) WHERE delivered_target_revision IS NULL',
  'CREATE INDEX agent_mail_inbox_input ON agent_mail_inbox(target_session_id,sequence)',
]);

export const KITE_SESSION_AGENT_INDEXES = Object.freeze([
  'agent_mail_target_sequence',
  'agent_nodes_parent',
  'agent_mail_outbox_pending',
  'agent_mail_inbox_input',
]);

// The persisted lineage Store 11 predates cross-Session mail. Keep its exact
// shape separate from the later schema even though both use the Agent tables.
const isCrossSessionMailStatement = (statement: string): boolean =>
  statement.startsWith('CREATE TABLE agent_mail_outbox (') ||
  statement.startsWith('CREATE TABLE agent_mail_inbox (') ||
  statement.startsWith('CREATE INDEX agent_mail_outbox_pending ') ||
  statement.startsWith('CREATE INDEX agent_mail_inbox_input ');

export const KITE_SESSION_AGENT_STORE11_DDL = Object.freeze(
  KITE_SESSION_AGENT_DDL.filter((statement) => !isCrossSessionMailStatement(statement)),
);
export const KITE_SESSION_AGENT_CROSS_SESSION_DDL = Object.freeze(
  KITE_SESSION_AGENT_DDL.filter(isCrossSessionMailStatement),
);
export const KITE_SESSION_AGENT_STORE11_INDEXES = Object.freeze([
  'agent_mail_target_sequence',
  'agent_nodes_parent',
] as const);
