import { lstatSync, readdirSync, realpathSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { assertCanonicalKiteDatabasePath } from './kite-home-runtime-file';
import { KiteSessionStoreOpenError } from './kite-session-runtime-file';

/** Known historical locations only. Discovery never opens a writer or creates a target. */
export function inspectKiteSessionStoreSources(databasePath: string): readonly string[] {
  const target = assertCanonicalKiteDatabasePath(databasePath, 'kite-session.sqlite');
  const root = dirname(target);
  const sources: string[] = [];
  const inspectFile = (path: string): void => {
    const stat = lstatSync(path, { throwIfNoEntry: false });
    const wal = lstatSync(`${path}-wal`, { throwIfNoEntry: false });
    if (wal && (!wal.isFile() || wal.isSymbolicLink() || wal.nlink !== 1)) {
      throw new KiteSessionStoreOpenError(
        'store_history_reconciliation_required',
        'Historical Store WAL cannot be safely inspected; the current Store was not opened.',
      );
    }
    if (!stat) {
      if (wal && wal.size > 0) sources.push(path);
      return;
    }
    if (
      !stat.isFile() ||
      stat.isSymbolicLink() ||
      stat.nlink !== 1 ||
      realpathSync.native(path) !== path ||
      (typeof process.getuid === 'function' && stat.uid !== process.getuid())
    ) {
      throw new KiteSessionStoreOpenError(
        'store_history_reconciliation_required',
        'A historical Store path cannot be safely inspected; the current Store was not opened.',
      );
    }
    // WAL may contain committed data even when the main file is empty or absent.
    if (stat.size > 0 || (wal && wal.size > 0)) sources.push(path);
  };
  inspectFile(join(root, 'kite.sqlite'));
  const profiles = join(root, 'source-profiles');
  const parent = lstatSync(profiles, { throwIfNoEntry: false });
  if (!parent) return Object.freeze(sources);
  if (
    !parent.isDirectory() ||
    parent.isSymbolicLink() ||
    realpathSync.native(profiles) !== profiles ||
    (typeof process.getuid === 'function' && parent.uid !== process.getuid())
  ) {
    throw new KiteSessionStoreOpenError(
      'store_history_reconciliation_required',
      'The historical Store directory cannot be safely inspected; the current Store was not opened.',
    );
  }
  for (const entry of readdirSync(profiles, { withFileTypes: true })) {
    // These are the only directory identities generated by the retired source resolver.
    if (!/^[a-f0-9]{32}$/u.test(entry.name)) continue;
    const directory = join(profiles, entry.name);
    const stat = lstatSync(directory);
    if (
      !stat.isDirectory() ||
      stat.isSymbolicLink() ||
      realpathSync.native(directory) !== directory ||
      (typeof process.getuid === 'function' && stat.uid !== process.getuid())
    ) {
      throw new KiteSessionStoreOpenError(
        'store_history_reconciliation_required',
        'A historical Store directory is unsafe; the current Store was not opened.',
      );
    }
    inspectFile(join(directory, 'kite-session.sqlite'));
  }
  return Object.freeze(sources.sort());
}

/** Startup preparation must resolve historical sources before presenting a complete directory. */
export function assertKiteSessionStoreSourcesReconciled(databasePath: string): void {
  if (inspectKiteSessionStoreSources(databasePath).length > 0) {
    throw new KiteSessionStoreOpenError(
      'store_history_reconciliation_required',
      'Historical session data exists outside the canonical Store; reconcile it before opening a new session directory.',
    );
  }
}
