import type { KiteWorkspaceIdentity } from '@kite-ai/kite-app-contract';
import { createLocalRuntimeServiceToken } from '@kite-ai/kite-local-runtime/service';
import {
  createKiteServiceCarrier,
  KITE_SERVICE_CONNECT_PATH,
  KITE_SERVICE_HISTORY_LIST_EVENTS_PATH,
  KITE_SERVICE_HISTORY_LIST_SESSIONS_PATH,
  KITE_SERVICE_HISTORY_LOAD_SESSION_PATH,
  KITE_SERVICE_INSTANCE_HANDSHAKE_PATH,
  type KiteServiceApplicationPort,
  type KiteServiceCarrier,
} from '../carrier';
import {
  KITE_SERVICE_CONTROLLER_GENERATION_HEADER,
  KITE_SERVICE_CONTROLLER_SESSION_HEADER,
} from '../carrier/native-loopback-carrier';
import {
  createWorkspaceWorkerCapabilityAuthority,
  createWorkspaceWorkerControlCarrier,
  KITE_WORKER_CLIENT_ID_HEADER,
  KITE_WORKER_CONNECTION_GENERATION_HEADER,
  KITE_WORKER_PURPOSE_HEADER,
  type WorkspaceWorkerCapabilityAuthority,
  type WorkspaceWorkerControlCarrier,
} from './control-carrier';
import {
  createWorkspaceWorkerControllerAdapter,
  type WorkspaceWorkerControllerAdapter,
} from './controller-adapter';
import type {
  WorkspaceWorkerActivityKind,
  WorkspaceWorkerActivityLease,
  WorkspaceWorkerIdleLifecycle,
} from './lifecycle';
import { createWorkspaceWorkerIdleLifecycle } from './lifecycle';
import type { WorkspaceWorkerControlIdentity } from './process-host';
import {
  createWorkspaceWorkerStoreContext,
  openWorkspaceWorkerStore,
  type WorkspaceWorkerStoreAuthority,
  type WorkspaceWorkerStoreContext,
  type WorkspaceWorkerStoreOwner,
  type WorkspaceWorkerStoreStorageOptions,
} from './store-owner';
import type { WorkspaceWorkerIdentity, WorkspaceWorkerOwnerLockPort } from './worker';

export interface WorkspaceWorkerApplicationFactoryInput {
  /** Fixed OS-user coordination root shared across explicit Kite homes. */
  readonly coordinationHome: import('@kite-ai/kite-local-runtime/service').KiteHomeIdentity;
  readonly workspace: KiteWorkspaceIdentity;
  readonly workerIdentity: WorkspaceWorkerIdentity;
  readonly storeContext: WorkspaceWorkerStoreContext;
  readonly storage: WorkspaceWorkerStoreOwner;
  readonly authority: WorkspaceWorkerStoreAuthority;
  /** Store 7 Controller adapter created by this Worker composition. */
  readonly controller?: WorkspaceWorkerControllerAdapter;
  readonly lifecycle: WorkspaceWorkerIdleLifecycle;
}

/**
 * A concrete app owner supplied by the Runtime composition layer. The owner must use the passed
 * Store/authority; this adapter never creates a second Host, Store, compatibility reader, or
 * fallback application.
 */
export interface WorkspaceWorkerApplicationOwner extends AsyncDisposable {
  readonly application: KiteServiceApplicationPort;
  /** Native-only Controller surface; Browser applications receive no reference to this owner. */
  readonly controller?: WorkspaceWorkerControllerAdapter;
  start(): Promise<void>;
  /** Optional owner-level cancellation used by signal shutdown. */
  readonly cancelAll?: (reason: string) => Promise<void>;
  /** Flush State/receipt/effect evidence before the Store is closed. */
  drain(): Promise<void>;
}

export interface WorkspaceWorkerRuntimeCompositionOptions {
  readonly home: import('@kite-ai/kite-local-runtime/service').KiteHomeIdentity;
  /** Fixed OS-user coordination root shared across explicit Kite homes. */
  readonly coordinationHome: import('@kite-ai/kite-local-runtime/service').KiteHomeIdentity;
  readonly workspace: KiteWorkspaceIdentity;
  readonly workerScopeId: string;
  readonly workerInstanceId: string;
  readonly buildId: string;
  readonly layoutGeneration: string;
  /** Manager-issued restart-scoped control credential; never generated by the child. */
  readonly controlCredential: string;
  readonly ownerLock: WorkspaceWorkerOwnerLockPort;
  readonly storageOptions?: WorkspaceWorkerStoreStorageOptions;
  readonly createApplication: (
    input: WorkspaceWorkerApplicationFactoryInput,
  ) => WorkspaceWorkerApplicationOwner | Promise<WorkspaceWorkerApplicationOwner>;
  readonly serverVersion?: string;
}

export type WorkspaceWorkerRuntimeShutdownResult = 'closed' | 'busy' | 'outcome_unknown';

export interface WorkspaceWorkerRuntimeComposition extends AsyncDisposable {
  readonly workerIdentity: WorkspaceWorkerIdentity;
  readonly controlIdentity: WorkspaceWorkerControlIdentity;
  readonly storeContext: WorkspaceWorkerStoreContext;
  readonly storage: WorkspaceWorkerStoreOwner;
  readonly authority: WorkspaceWorkerStoreAuthority;
  /** The Worker-owned Controller adapter over the injected Store 7 authority. */
  readonly controller: WorkspaceWorkerControllerAdapter;
  readonly lifecycle: WorkspaceWorkerIdleLifecycle;
  readonly origin: string;
  readonly rpcUrl: string;
  /** Internal control origin; never placed in the Worker readiness/Coordinator/browser DTO. */
  readonly controlOrigin: string;
  readonly controlCredential: string;
  readonly requestShutdown: (reason: string) => Promise<WorkspaceWorkerRuntimeShutdownResult>;
  readonly waitForShutdown: () => Promise<void>;
  readonly acquireActivity: (
    kind: WorkspaceWorkerActivityKind,
    activityId: string,
  ) => WorkspaceWorkerActivityLease;
  close(): Promise<void>;
}

/**
 * Compose one foreground Worker around one exact Store 7 binding and one application owner.
 * Owner-lock acquisition is deliberately the first side effect before Store open or Runtime
 * composition. Store admission is read-only here; layout migration/materialization belongs to the
 * Coordinator/layout owner and missing evidence fails closed.
 */
export async function createWorkspaceWorkerRuntimeComposition(
  options: WorkspaceWorkerRuntimeCompositionOptions,
): Promise<WorkspaceWorkerRuntimeComposition> {
  const workspace = createWorkspaceWorkerStoreContext({
    home: options.home,
    workspace: options.workspace,
    workerScopeId: options.workerScopeId,
    layoutGeneration: options.layoutGeneration,
  });
  const workerIdentity: WorkspaceWorkerIdentity = Object.freeze({
    workerScopeId: options.workerScopeId,
    workerInstanceId: options.workerInstanceId,
    buildId: options.buildId,
    workspace: options.workspace,
  });
  const controlIdentity: WorkspaceWorkerControlIdentity = Object.freeze({
    workerScopeId: options.workerScopeId,
    workerInstanceId: options.workerInstanceId,
    buildId: options.buildId,
    workspace: options.workspace,
  });

  const ownerLock = await options.ownerLock.acquire(workerIdentity);
  if (!sameWorkerIdentity(ownerLock.identity, workerIdentity)) {
    await Promise.resolve(ownerLock[Symbol.asyncDispose]()).catch(() => undefined);
    throw new Error('Workspace Worker owner lock identity mismatches the admitted Workspace.');
  }

  let storage: WorkspaceWorkerStoreOwner | undefined;
  let applicationOwner: WorkspaceWorkerApplicationOwner | undefined;
  let dataCarrier: KiteServiceCarrier | undefined;
  let controlCarrier: WorkspaceWorkerControlCarrier | undefined;
  let capabilityAuthority: WorkspaceWorkerCapabilityAuthority | undefined;
  let ready = false;
  let closed = false;
  let closePromise: Promise<void> | undefined;
  let resolveShutdown!: () => void;
  const shutdown = new Promise<void>((resolvePromise) => {
    resolveShutdown = resolvePromise;
  });
  const clientActivities = new Map<string, WorkspaceWorkerActivityLease>();
  let lifecycle!: WorkspaceWorkerIdleLifecycle;

  const closeOwners = async (): Promise<void> => {
    if (closed) return;
    closed = true;
    ready = false;
    const failures: unknown[] = [];
    for (const lease of clientActivities.values()) {
      try {
        await lease[Symbol.asyncDispose]();
      } catch (error) {
        failures.push(error);
      }
    }
    clientActivities.clear();
    try {
      await dataCarrier?.close();
    } catch (error) {
      failures.push(error);
    }
    dataCarrier = undefined;
    try {
      await controlCarrier?.close();
    } catch (error) {
      failures.push(error);
    }
    controlCarrier = undefined;
    capabilityAuthority?.close();
    capabilityAuthority = undefined;
    try {
      await applicationOwner?.[Symbol.asyncDispose]();
    } catch (error) {
      failures.push(error);
    }
    applicationOwner = undefined;
    try {
      storage?.close();
    } catch (error) {
      failures.push(error);
    }
    storage = undefined;
    try {
      await ownerLock[Symbol.asyncDispose]();
    } catch (error) {
      failures.push(error);
    }
    resolveShutdown();
    if (failures.length === 1) throw failures[0];
    if (failures.length > 1) throw new AggregateError(failures);
  };

  lifecycle = createWorkspaceWorkerIdleLifecycle({
    drain: async () => {
      await applicationOwner?.drain();
    },
    close: closeOwners,
  });

  try {
    storage = openWorkspaceWorkerStore(workspace, {
      ...(options.storageOptions ? { storageOptions: options.storageOptions } : {}),
    });
    const authority = storage.workspaceAuthority;
    const controller = createWorkspaceWorkerControllerAdapter({
      authority,
      workerInstanceId: workerIdentity.workerInstanceId,
    });
    applicationOwner = await options.createApplication({
      coordinationHome: options.coordinationHome,
      workspace: options.workspace,
      workerIdentity,
      storeContext: workspace,
      storage,
      authority,
      controller,
      lifecycle,
    });
    await applicationOwner.start();

    const wrappedApplication: KiteServiceApplicationPort = Object.freeze({
      ...applicationOwner.application,
      // Worker control is a separate exact carrier; the broad Service control route is not
      // exposed through the Runtime data-plane listener.
      control: undefined,
      onConnectionBound: (connectionId: string, admittedWorkspace: KiteWorkspaceIdentity) => {
        const activity = lifecycle.acquire('client', connectionId);
        clientActivities.set(connectionId, activity);
        applicationOwner?.application.onConnectionBound?.(connectionId, admittedWorkspace);
      },
      onConnectionClosed: (connectionId: string) => {
        const activity = clientActivities.get(connectionId);
        if (activity) {
          clientActivities.delete(connectionId);
          void Promise.resolve(activity[Symbol.asyncDispose]()).catch(() => undefined);
        }
        applicationOwner?.application.onConnectionClosed?.(connectionId);
      },
    });
    capabilityAuthority = createWorkspaceWorkerCapabilityAuthority({
      identity: controlIdentity,
      requestIdleStop: async () => {
        const result = await lifecycle.stopIfIdle();
        return result;
      },
    });
    // This token is only the carrier's internal constructor material. Every caller-facing access
    // request is checked through the Worker capability verifier below.
    const accessToken = createLocalRuntimeServiceToken();
    const dataControlToken = createLocalRuntimeServiceToken();
    dataCarrier = createKiteServiceCarrier({
      application: wrappedApplication,
      instanceId: options.workerInstanceId,
      serverVersion: options.serverVersion ?? 'kite-workspace-worker-v1',
      buildId: options.buildId,
      accessToken,
      controlToken: dataControlToken,
      accessTokenVerifier: ({ token, request, pathname }) => {
        const clientId = request.headers.get(KITE_WORKER_CLIENT_ID_HEADER);
        const generationValue = request.headers.get(KITE_WORKER_CONNECTION_GENERATION_HEADER);
        const purpose = request.headers.get(KITE_WORKER_PURPOSE_HEADER);
        if (
          !clientId ||
          !generationValue ||
          !/^\d+$/u.test(generationValue) ||
          !Number.isSafeInteger(Number(generationValue)) ||
          (purpose !== 'native_client' && purpose !== 'web_observer')
        ) {
          return false;
        }
        if (
          purpose === 'web_observer' &&
          pathname !== KITE_SERVICE_INSTANCE_HANDSHAKE_PATH &&
          pathname !== KITE_SERVICE_CONNECT_PATH &&
          pathname !== KITE_SERVICE_HISTORY_LIST_SESSIONS_PATH &&
          pathname !== KITE_SERVICE_HISTORY_LIST_EVENTS_PATH &&
          pathname !== KITE_SERVICE_HISTORY_LOAD_SESSION_PATH
        ) {
          return false;
        }
        return capabilityAuthority!.verifyConnectionCapability(
          {
            workerScopeId: controlIdentity.workerScopeId,
            workerInstanceId: controlIdentity.workerInstanceId,
            workspaceDigest: controlIdentity.workspace.workspaceDigest,
            clientId,
            connectionGeneration: Number(generationValue),
            purpose,
            secret: token,
          },
          { consume: pathname === KITE_SERVICE_CONNECT_PATH },
        );
      },
      connectionKindForRequest: (request) => {
        const purpose = request.headers.get(KITE_WORKER_PURPOSE_HEADER);
        return purpose === 'native_client' || purpose === 'web_observer' ? purpose : undefined;
      },
      connectionBindingForRequest: (request) => {
        const purpose = request.headers.get(KITE_WORKER_PURPOSE_HEADER);
        if (purpose !== 'native_client') return undefined;
        const clientId = request.headers.get(KITE_WORKER_CLIENT_ID_HEADER);
        const generationValue = request.headers.get(KITE_WORKER_CONNECTION_GENERATION_HEADER);
        if (
          !safeWorkerText(clientId) ||
          !/^\d+$/u.test(generationValue ?? '') ||
          !positiveWorkerGeneration(Number(generationValue))
        ) {
          return undefined;
        }
        const binding = {
          clientId,
          connectionGeneration: Number(generationValue),
          workerInstanceId: controlIdentity.workerInstanceId,
        } as const;
        const controllerSessionId = request.headers.get(KITE_SERVICE_CONTROLLER_SESSION_HEADER);
        const controllerGenerationValue = request.headers.get(
          KITE_SERVICE_CONTROLLER_GENERATION_HEADER,
        );
        if (
          safeWorkerText(controllerSessionId) &&
          /^\d+$/u.test(controllerGenerationValue ?? '') &&
          positiveWorkerGeneration(Number(controllerGenerationValue))
        ) {
          try {
            const lease = controller.observer.lease(controllerSessionId);
            if (
              lease?.status === 'active' &&
              lease.clientId === clientId &&
              lease.connectionGeneration === Number(generationValue) &&
              lease.workerInstanceId === controlIdentity.workerInstanceId &&
              lease.controllerGeneration === Number(controllerGenerationValue)
            ) {
              return Object.freeze({
                ...binding,
                controllerSessionId,
                controllerGeneration: Number(controllerGenerationValue),
              });
            }
          } catch {
            // The route remains an Observer connection when Controller state is unavailable.
          }
        }
        return Object.freeze(binding);
      },
      isReady: () => ready,
    });
    controlCarrier = createWorkspaceWorkerControlCarrier({
      identity: controlIdentity,
      authority: capabilityAuthority,
      credential: options.controlCredential,
      directoryOutbox: storage.directoryOutbox,
    });
    lifecycle.markReady();
    ready = true;
    return Object.freeze({
      workerIdentity,
      controlIdentity,
      storeContext: workspace,
      storage,
      authority,
      controller,
      lifecycle,
      origin: dataCarrier.origin,
      rpcUrl: dataCarrier.rpcUrl,
      controlOrigin: controlCarrier.origin,
      controlCredential: options.controlCredential,
      requestShutdown: async (reason: string) => {
        if (!reason || reason.length > 512) return 'outcome_unknown' as const;
        try {
          await applicationOwner?.cancelAll?.(reason);
        } catch {
          // The narrow Service application port may not own a cancellation hook. Its lifecycle
          // activity holds still prevent an unsafe force-close.
        }
        try {
          return (await lifecycle.stopIfIdle()) as WorkspaceWorkerRuntimeShutdownResult;
        } catch {
          return 'outcome_unknown' as const;
        }
      },
      waitForShutdown: () => shutdown,
      acquireActivity: (kind: WorkspaceWorkerActivityKind, activityId: string) =>
        lifecycle.acquire(kind, activityId),
      close: async () => {
        if (closePromise) return closePromise;
        closePromise = (async () => {
          const result = await lifecycle.stopIfIdle();
          if (result === 'busy') throw new Error('Workspace Worker is busy.');
        })();
        return closePromise;
      },
      [Symbol.asyncDispose]() {
        return this.close();
      },
    });
  } catch (error) {
    try {
      await closeOwners();
    } catch {
      // Preserve the startup error while the owner cleanup attempts remain best effort.
    }
    throw error;
  }
}

function sameWorkerIdentity(
  left: WorkspaceWorkerIdentity,
  right: WorkspaceWorkerIdentity,
): boolean {
  return (
    left.workerScopeId === right.workerScopeId &&
    left.workerInstanceId === right.workerInstanceId &&
    left.buildId === right.buildId &&
    left.workspace.canonicalPath === right.workspace.canonicalPath &&
    left.workspace.projectId === right.workspace.projectId &&
    left.workspace.workspaceDigest === right.workspace.workspaceDigest
  );
}

function safeWorkerText(value: string | null): value is string {
  return value !== null && value.length > 0 && value.length <= 512 && !/\p{Cc}/u.test(value);
}

function positiveWorkerGeneration(value: number): boolean {
  return Number.isSafeInteger(value) && value >= 1;
}
