/**
 * PTY System Test — Plan Draft (write_plan) Rendering
 *
 * Verifies that when the agent calls write_plan in planning phase,
 * the TUI renders a tool_card with the plan content and does NOT trigger
 * a plan_review interrupt (that's exit_plan_mode's job in v2).
 *
 * The full write_plan → exit_plan_mode → approve/revise flow is tested
 * at the unit/integration level because the dynamic planId generated by
 * write_plan cannot be predicted by mock models. See:
 *   - tests/runtime/plan-state.test.ts
 *   - tests/runtime/plan-actions.test.ts
 *   - tests/runtime/tool-controller.test.ts
 */

import { afterAll, beforeAll, describe, expect, test } from 'bun:test';
import { createMockModelServer } from '../harness/fixtures';
import { typeText, waitForRequestMessage } from '../harness/input-helpers';
import { createTuiSystemJourney } from '../harness/journey';
import { type PtyProcess, spawnTui } from '../harness/pty-process';
import { screenContains, stripAnsi, waitForText } from '../harness/terminal-screen';
import { createTestWorkspace } from '../harness/test-workspace';

const TIMEOUT = 30000;

describe('TUI PTY System — Plan Draft (write_plan)', () => {
  const journey = createTuiSystemJourney();
  const step = journey.step;
  let tui: PtyProcess;
  let server: ReturnType<typeof createMockModelServer>;
  let workspace: ReturnType<typeof createTestWorkspace>;

  beforeAll(async () => {
    server = createMockModelServer();
    workspace = createTestWorkspace();

    // Shared mock responses — write_plan in planning phase.
    // Response #1: write_plan tool call with v2 args
    // Response #2: agent text after drafting
    // Response #3-7: spare responses for generateSessionName + retries
    server.setResponses([
      {
        message: {
          content: 'Let me draft a plan.',
          tool_calls: [
            {
              id: 'call_write_1',
              name: 'write_plan',
              args: {
                title: 'Test Draft Plan',
                body_markdown: 'Implement the feature step by step with careful testing.',
                steps: [
                  { id: 'setup', title: 'Set up project structure' },
                  { id: 'core', title: 'Implement core logic' },
                  { id: 'test', title: 'Write tests' },
                ],
              },
            },
          ],
        },
      },
      { message: { content: 'Plan draft saved. Ready for review when you are.' } },
      { message: { content: 'Spare 1' } },
      { message: { content: 'Spare 2' } },
      { message: { content: 'Spare 3' } },
      { message: { content: 'Spare 4' } },
      { message: { content: 'Spare 5' } },
    ]);

    tui = spawnTui({ cols: 120, rows: 40, mockServer: server, workspace });
    await waitForText(() => tui.outputSinceLastAction(), '❯', 15000);
    tui.setRawMode(true);
  });

  afterAll(async () => {
    server?.stop();
    await tui?.killAndWait();
    workspace?.cleanup();
  });

  // ── write_plan in planning phase renders plan content ───

  step(
    'write_plan renders plan content in planning phase',
    async () => {
      // Enter planning phase via /plan command
      await typeText(tui, '/plan Draft a plan for testing');
      tui.write('\r');
      await waitForRequestMessage(server, 'Draft a plan for testing', 15000);

      // Wait for the plan draft follow-up text
      await waitForText(() => tui.outputSinceLastAction(), 'Plan draft saved', 15000);

      const output = tui.viewport();
      const clean = stripAnsi(output);
      console.log('  output after write_plan:', clean.slice(-2000));

      // Plan content should appear in the rendered output
      expect(clean.includes('Test Draft Plan')).toBe(true);

      // Plan review UI should NOT be shown (write_plan does not trigger review)
      expect(clean.includes('Review the plan above and choose')).toBe(false);

      // TUI prompt should be back
      expect(clean.includes('❯')).toBe(true);
    },
    TIMEOUT,
  );

  // ── write_plan in building phase is rejected ─────────────

  step(
    'write_plan is rejected in building phase',
    async () => {
      // Submit a new message (in building phase — default mode)
      await typeText(tui, 'Try to write a plan now');
      tui.write('\r');
      await waitForRequestMessage(server, 'Try to write a plan now', 15000);

      await waitForText(() => tui.outputSinceLastAction(), '❯', 15000);

      const output = tui.viewport();
      const clean = stripAnsi(output);
      console.log('  output after building phase write_plan attempt:', clean.slice(-1500));

      // TUI should still be responsive (no crash)
      expect(screenContains(output, '❯')).toBe(true);
    },
    TIMEOUT,
  );
  test('runs the complete stateful journey', () => journey.run(), 170_000);
});
