export interface CgroupPidsRunnerV1 {
  mechanism: 'systemd_user_scope_tasks_max';
  executable: string;
  /** Exact argv-only authority used by the Runtime consumer for kill/reconcile. */
  systemctlExecutable: string;
}

export interface CgroupPidsScopeIdentityV1 {
  readonly unitName: string;
  readonly runnerExecutable: string;
  readonly systemctlExecutable: string;
  readonly cgroupPath: string;
}

const CGROUP_PIDS_SCOPE_ID_V1 =
  /^(?:[0-9a-f]{64}|[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})$/;

/** A systemd scope name is generated by the Runtime, never accepted from a model/tool. */
export function createCgroupPidsUnitNameV1(identity: string): string {
  if (!CGROUP_PIDS_SCOPE_ID_V1.test(identity)) {
    throw new Error('cgroup pids unit identity is invalid.');
  }
  return `kite-sandbox-${identity}.scope`;
}

export function isCgroupPidsUnitNameV1(value: unknown): value is string {
  if (
    typeof value !== 'string' ||
    !value.startsWith('kite-sandbox-') ||
    !value.endsWith('.scope')
  ) {
    return false;
  }
  return CGROUP_PIDS_SCOPE_ID_V1.test(value.slice('kite-sandbox-'.length, -'.scope'.length));
}

export function isCgroupPidsPathV1(value: unknown, unitName: string): value is string {
  if (!isCgroupPidsUnitNameV1(unitName) || typeof value !== 'string') return false;
  if (!value.startsWith('/') || value.includes('\0')) return false;
  const split = value.split('/');
  if (split[0] !== '' || split.slice(1).some((part) => part.length === 0)) return false;
  const parts = split.slice(1);
  return parts.length > 0 && parts.at(-1) === unitName && parts.every(isSafeCgroupPathPartV1);
}

export function isCgroupPidsExecutablePathV1(value: unknown): value is string {
  if (
    typeof value !== 'string' ||
    !value.startsWith('/') ||
    value.endsWith('/') ||
    value.includes('\0') ||
    /\s/.test(value)
  ) {
    return false;
  }
  const parts = value.split('/').slice(1);
  return (
    parts.length > 0 &&
    parts.every(
      (part) =>
        part.length > 0 && part !== '.' && part !== '..' && /^[A-Za-z0-9_+@.-]+$/.test(part),
    )
  );
}

/** Pure argv projection for a Runtime-qualified cgroup-v2 runner. */
export function buildCgroupPidsInvocationV1(input: {
  runner: CgroupPidsRunnerV1;
  maxTasks: number;
  command: readonly string[];
  unitName: string;
}): string[] {
  if (!Number.isSafeInteger(input.maxTasks) || input.maxTasks < 1) {
    throw new Error('cgroup pids maxTasks must be a positive integer.');
  }
  if (
    input.command.length === 0 ||
    input.command.some(
      (part) => typeof part !== 'string' || part.length === 0 || part.includes('\0'),
    )
  ) {
    throw new Error('cgroup pids invocation requires a non-empty command.');
  }
  if (!isCgroupPidsUnitNameV1(input.unitName)) {
    throw new Error('cgroup pids invocation requires an exact Runtime-owned unit name.');
  }
  if (
    !isCgroupPidsExecutablePathV1(input.runner.executable) ||
    !isCgroupPidsExecutablePathV1(input.runner.systemctlExecutable)
  ) {
    throw new Error('cgroup pids runner executable identity is invalid.');
  }
  return [
    input.runner.executable,
    '--user',
    '--scope',
    '--quiet',
    '--collect',
    '--slice-inherit',
    '--expand-environment=no',
    '--property=TasksAccounting=yes',
    `--property=TasksMax=${input.maxTasks}`,
    `--unit=${input.unitName}`,
    '--',
    ...input.command,
  ];
}

function isSafeCgroupPathPartV1(value: string): boolean {
  return value !== '.' && value !== '..' && /^[A-Za-z0-9_.:@-]+$/.test(value);
}
